#!/bin/bash
cowsay -f eyes " VPSMOD Nexuser" | lolcat
figlet ..Nexuser.. | lolcat ;
apt install git  -y;
apt install npm  -y ;
sudo apt install -y make python build-essential;
cd /root/ ;
git clone https://github.com/botgram/shell-bot.git;
cd shell-bot;
npm install;
sleep 2;
echo "Instalado Con exito" ;
sleep 2;
echo "Iniciando Bot.";
sleep 2;
echo "A continuacion pon el API KEY DEL BOT y envia el mensaje Hello "
sleep 2 ;
node server ;
sleep 2;
echo "Finalizado Con exito";
nohup node server & clean ;
sleep 2 ;
echo "Bot iniciado Con exito"

