#!/bin/bash
cowsay -f eyes " VPSMOD Nexuser" | lolcat
figlet ..Nexuser.. | lolcat ;
apt install git ;
apt install npm ;
sudo apt install -y make python build-essential;
git clone https://github.com/botgram/shell-bot.git;
cd shell-bot;
npm install;

