#!/bin/sh
#Alias : Nexuser
#SCRIPT OFICIAL Nexuser|Plus
# Formato Creado por @Nexuser | 
clear&&clear
fun_ip () {
MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
[[ "$MEU_IP" != "$MEU_IP2" ]] && IP="$MEU_IP2" || IP="$MEU_IP"
trojanport=`lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN" | grep trojan | awk '{print substr($9,3); }' > /tmp/trojan.txt && echo | cat /tmp/trojan.txt | tr '\n' ' ' > /bin/ejecutar/trojanports.txt && cat /bin/ejecutar/trojanports.txt`;
troport=$(cat /bin/ejecutar/trojanports.txt  | sed 's/\s\+/,/g' | cut -d , -f1)
portFTP=$(lsof -V -i tcp -P -n | grep apache2 | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN" | cut -d: -f2 | cut -d' ' -f1 | uniq)
portFTP=$(echo ${portFTP} | sed 's/\s\+/,/g' | cut -d , -f1)
}
#FUN_BAR
fun_bar () { 
comando="$1"  
_=$( $comando > /dev/null 2>&1 ) & > /dev/null 
pid=$! 
while [[ -d /proc/$pid ]]; do 
echo -ne " \033[1;33m["    
for((i=0; i<20; i++)); do    
echo -ne "\033[1;31m##"    
sleep 0.5    
done 
echo -ne "\033[1;33m]" 
sleep 1s 
echo tput cuu1 tput dl1 
done 
echo -e " \033[1;33m[\033[1;31m########################################\033[1;33m] - \033[1;32m100%\033[0m" 
sleep 1s 
} 

install_ini () {
add-apt-repository universe
apt update -y; apt upgrade -y
clear
msg -bar3
echo -e "\033[92m        -- INSTALANDO PAQUETES NECESARIOS -- "
msg -bar3
#bc
[[ $(dpkg --get-selections|grep -w "golang-go"|head -1) ]] || apt-get install golang-go -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "golang-go"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "golang-go"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install golang-go............ $ESTATUS "
#jq
[[ $(dpkg --get-selections|grep -w "jq"|head -1) ]] || apt-get install jq -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "jq"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "jq"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install jq................... $ESTATUS "
#curl
[[ $(dpkg --get-selections|grep -w "curl"|head -1) ]] || apt-get install curl -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "curl"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "curl"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install curl................. $ESTATUS "
#npm
[[ $(dpkg --get-selections|grep -w "npm"|head -1) ]] || apt-get install npm -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "npm"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "npm"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install npm.................. $ESTATUS "
#nodejs
[[ $(dpkg --get-selections|grep -w "nodejs"|head -1) ]] || apt-get install nodejs -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "nodejs"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "nodejs"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install nodejs............... $ESTATUS "
#socat
[[ $(dpkg --get-selections|grep -w "socat"|head -1) ]] || apt-get install socat -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "socat"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "socat"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install socat................ $ESTATUS "
#netcat
[[ $(dpkg --get-selections|grep -w "netcat"|head -1) ]] || apt-get install netcat -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "netcat"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "netcat"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install netcat............... $ESTATUS "
#net-tools
[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || apt-get net-tools -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install net-tools............ $ESTATUS "
#figlet
[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || apt-get install figlet -y &>/dev/null
[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || ESTATUS=`echo -e "\033[91mFALLO DE INSTALACION"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] && ESTATUS=`echo -e "\033[92mINSTALADO"` &>/dev/null
echo -e "\033[97m  # apt-get install figlet............... $ESTATUS "
msg -bar3
echo -e "\033[92m La instalacion de paquetes necesarios a finalizado"
msg -bar3
echo -e "\033[97m Si la instalacion de paquetes tiene fallas"
echo -ne "\033[97m Puede intentar de nuevo [s/n]: "
read inst
[[ $inst = @(s|S|y|Y) ]] && install_ini
echo -ne "\033[97m Deseas agregar Menu Clash Rapido [s/n]: "
read insta
[[ $insta = @(s|S|y|Y) ]] && enttrada
}


fun_insta(){
fun_ip
install_ini
msg -bar3
killall clash 1> /dev/null 2> /dev/null
echo -e " ➣ Creando Directorios y Archivos"
msg -bar3 
[[ -d /root/.config ]] && rm -rf /root/.config/* || mkdir /root/.config 
mkdir /root/.config/clash 1> /dev/null 2> /dev/null
last_version=$(curl -Ls "https://api.github.com/repos/Dreamacro/clash/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
arch=$(arch)
if [[ $arch == "x86_64" || $arch == "x64" || $arch == "amd64" ]]; then
  arch="amd64"
elif [[ $arch == "aarch64" || $arch == "arm64" ]]; then
  arch="arm64"
else
  arch="amd64"
fi
wget -N --no-check-certificate -O /root/.config/clash/clash.gz https://github.com/Dreamacro/clash/releases/download/${last_version}/clash-linux-${arch}-${last_version}.gz
gzip -d /root/.config/clash/clash.gz
chmod +x /root/.config/clash/clash
echo -e " ➣ Clonando Repositorio Original Dreamacro "
go get -u -v github.com/Dreamacro/clash
clear
}



[[ -e /bin/ejecutar/msg ]] && source /bin/ejecutar/msg || source <(curl -sSL https://raw.githubusercontent.com/Nexuser/Nexuser-Script/master/msg-bar/msg)
numero='^[0-9]+$'
hora=$(printf '%(%H:%M:%S)T') 
fecha=$(printf '%(%D)T')
[[ ! -d /bin/ejecutar/clashFiles ]] && mkdir /bin/ejecutar/clashFiles
clashFiles='/bin/ejecutar/clashFiles/'

INITClash(){
msg -bar
conFIN
read -p "Ingrese Nombre del Poster WEB de la configuracion: " cocolon
[[ -e /root/.config/clash/config.yaml ]] && sed -i "s%/_dAtE/%${fecha}%g" /root/.config/clash/config.yaml
[[ -e /root/.config/clash/config.yaml ]] && sed -i "s/_h0rA/${hora}/g" /root/.config/clash/config.yaml
cp /root/.config/clash/config.yaml /var/www/html/$cocolon.yaml && chmod +x /var/www/html/$cocolon.yaml
service apache2 restart
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m \033[1;33m"
echo -e "\033[1;33mClash Server Instalado"
echo -e "-------------------------------------------------------"
echo -e "		\033[4;31mNOTA importante\033[0m"
echo -e "Recuerda Descargar el Fichero, o cargarlo como URL!!"
echo -e "-------------------------------------------------------"
echo -e " \033[0;31mSi Usas Clash For Android, Ultima Version  "
echo -e "  Para luego usar el Link del Fichero, y puedas ."
echo -e " Descargarlo desde cualquier sitio con acceso WEB"
echo -e "        Link Clash Valido por 30 minutos "
echo -e "    Link : \033[1;42m  http://$IP:${portFTP}/$cocolon.yaml\033[0m"
echo -e "-------------------------------------------------------"
#read -p "PRESIONA ENTER PARA CARGAR ONLINE"
echo -e "\033[1;32mRuta de Configuracion: /root/.config/clash/config.yaml"
echo -e "\033[1;31mPRESIONE ENTER PARA CONTINUAR\033[0m"
scr=$(echo $(($RANDOM*3))|head -c 3)
unset yesno
echo -e " ENLACE VALIDO POR 30 MINUTOS? " 
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
[[ ${yesno} = @(s|S|y|Y) ]] &&  { 
killall clash > /dev/null &1>&2
screen -dmS clashse_$cocolon /root/.config/clash/clash
echo '#!/bin/bash -e' > /root/.config/clash/$cocolon.sh
echo "sleep 1800s" >> /root/.config/clash/$cocolon.sh && echo -e " ACTIVO POR 30 MINUTOS "  || echo " Validacion Incorrecta "
echo "mv /var/www/html/$cocolon.yaml ${clashFiles}$cocolon.yaml" >> /root/.config/clash/$cocolon.sh
echo 'echo "Fichero removido a ${clashFiles}$cocolon.yaml"' >> /root/.config/clash/$cocolon.sh
echo "service apache2 restart" >> /root/.config/clash/$cocolon.sh
echo "rm -f /root/.config/clash/$cocolon.sh" >> /root/.config/clash/$cocolon.sh
echo 'exit' >> /root/.config/clash/$cocolon.sh && screen -dmS clash${scr} bash /root/.config/clash/$cocolon.sh
} 
echo -e "Proceso Finalizado"

}

configINIT_rule () {
mode=$1
[[ -z ${mode} ]] && exit
unset tropass
echo '#SCRIPT OFICIAL Nexuser|Plus
# Formato Creado por @Nexuser | +593987072611 Whatsapp Personal
# Creado el _dAtE - _h0rA
port: 8080
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: "0.0.0.0:9090"
secret: ""

dns:
  enable: true
  listen: :53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 45.71.185.100
    - 204.199.156.138
    - 1.1.1.1
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP    
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

# Clash for Windows
cfw-bypass:
  - qq.com
  - music.163.com
  - "*.music.126.net"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000
    
proxy-groups:
- name: "Nexuser-ADM"
  type: select
  proxies:    ' > /root/.config/clash/config.yaml
#sed -i "s/+/'/g"  /root/.config/clash/config.yaml
foc=1
ConfTrojINI
foc=1
unset yesno
ConfV2RINI
}

configINIT_global () {
mode=$1
[[ -z ${mode} ]] && exit
unset tropass
echo '#SCRIPT OFICIAL Nexuser|Plus
# Formato Creado por @Nexuser | +593987072611 Whatsapp Personal
# Creado el _dAtE - _h0rA
port: 8080
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: global
log-level: info
external-controller: "0.0.0.0:9090"
secret: ""
dns:
  enable: true
  listen: :53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 45.71.185.100
    - 204.199.156.138
    - 1.1.1.1
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP    
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

# Clash for Windows
cfw-bypass:
  - qq.com
  - music.163.com
  - "*.music.126.net"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000   
 ' > /root/.config/clash/config.yaml
#sed -i "s/+/'/g"  /root/.config/clash/config.yaml
foc=1
ConfTrojINI
unset yesno
foc=1
ConfV2RINI
}

proxyTRO() {
fun_ip
[[ $mode = 1 ]] && echo -e "    - $1" >> /root/.config/clash/config.yaml
proTRO+="- name: $1\n  type: trojan\n  server: ${IP}\n  port: ${troport}\n  password: $2\n  udp: true\n  sni: $3\n  alpn:\n  - h2\n  - http/1.1\n  skip-cert-verify: true\n\n" 
  }

ConfTrojINI() {
echo -e " DESEAS AÑADIR TU ${foc} CONFIG TROJAN " 
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p " [S/N]: " yesno

tput cuu1 && tput dl1
done
[[ ${yesno} = @(s|S|y|Y) ]] &&  { 
unset yesno
foc=$(($foc + 1))
echo -ne "\033[1;33m ➣ PERFIL TROJAN CLASH "
read -p ": " nameperfil
msg -bar3
[[ -z ${tropass} ]] && view_usert || { 
echo -e " USER ${tropass}"
msg -bar3
}
echo -ne "\033[1;33m ➣ SNI o HOST "
read -p ": " trosni
msg -bar3
proxyTRO ${nameperfil} ${tropass} ${trosni}
ConfTrojINI
								}
}

proxyV2R() {
#proxyV2R ${nameperfil} ${trosni} ${uid} ${aluuiid} ${net} ${parche} ${v2port}
fun_ip
[[ $mode = 1 ]] && echo -e "    - $1" >> /root/.config/clash/config.yaml
proV2R+="- name: $1\n  type: vmess\n  server: ${IP}\n  port: $7\n  uuid: $3\n  alterId: $4\n  cipher: auto\n  udp: true\n  tls: true\n  skip-cert-verify: true\n  servername: $2\n  network: $5\n  ws-opts:  \n       path: $6\n       headers:\n         Host: $2\n  \n\n" 
  }
  
proxyV2Rgprc() {
#config=/usr/local/x-ui/bin/config.json
#cat $config | jq .inbounds[].settings.clients | grep id
#proxyV2R ${nameperfil} ${trosni} ${uid} ${aluuiid} ${net} ${parche} ${v2port}
fun_ip
[[ $mode = 1 ]] && echo -e "    - $1" >> /root/.config/clash/config.yaml
proV2R+="
- name: $1\n  server: ${IP}\n  port: $7\n  type: vmess\n  uuid: $3\n  alterId: $4\n  cipher: auto\n  tls: true\n  skip-cert-verify: true\n  network: grpc\n  servername: $2\n  grpc-opts:\n    grpc-mode: gun\n    grpc-service-name: $6\n  udp: true"
  }

ConfV2RINI() {
echo -e " DESEAS AÑADIR TU ${foc} CONFIG V2RAY " 
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
[[ ${yesno} = @(s|S|y|Y) ]] &&  { 
unset yesno
foc=$(($foc + 1))
echo -ne "\033[1;33m ➣ PERFIL V2RAY CLASH "
read -p ": " nameperfil
msg -bar3
[[ -z ${uid} ]] && view_user || { 
echo -e " USER ${ps}"
msg -bar3
}
echo -ne "\033[1;33m ➣ SNI o HOST "
read -p ": " trosni
msg -bar3

		ps=$(jq .inbounds[].settings.clients[$opcion].email $config) && [[ $ps = null ]] && ps="default"
		uid=$(jq .inbounds[].settings.clients[$opcion].id $config)
		aluuiid=$(jq .inbounds[].settings.clients[$opcion].alterId $config)
		add=$(jq '.inbounds[].domain' $config) && [[ $add = null ]] && add=$(wget -qO- ipv4.icanhazip.com)
		host=$(jq '.inbounds[].streamSettings.wsSettings.headers.Host' $config) && [[ $host = null ]] && host=''
		net=$(jq '.inbounds[].streamSettings.network' $config)
		parche=$(jq -r .inbounds[].streamSettings.wsSettings.path $config) && [[ $path = null ]] && parche='' 
		v2port=$(jq '.inbounds[].port' $config)
		tls=$(jq '.inbounds[].streamSettings.security' $config)
		[[ $net = '"grpc"' ]] && path=$(jq '.inbounds[].streamSettings.grpcSettings.serviceName'  $config) || path=$(jq '.inbounds[].streamSettings.wsSettings.path' $config)
		addip=$(wget -qO- ifconfig.me)

[[ $net = '"grpc"' ]] && {
proxyV2Rgprc ${nameperfil} ${trosni} ${uid} ${aluuiid} ${net} ${path} ${v2port}
} || {
proxyV2R ${nameperfil} ${trosni} ${uid} ${aluuiid} ${net} ${parche} ${v2port}
}

ConfV2RINI
								}
}

confRULE() {
[[ $mode = 1 ]] && echo -e '
  url: http://www.gstatic.com/generate_204
  interval: 300
 
###################################
# Nexuser-ADM

# By Nexuser By CGH
- name: "【 ✵ 𝚂𝚎𝚛𝚟𝚎𝚛-𝙿𝚁𝙴𝙼𝙸𝚄𝙼 ✵ 】"
  type: select
  proxies: 
    - "Nexuser-ADM"

#- name: "【 📱 +593987072611 】"
#  type: select
#  proxies:
#    - "Nexuser-ADM"

Rule:
# Unbreak
# > Google
- DOMAIN-SUFFIX,googletraveladservices.com,Nexuser-ADM
- DOMAIN,dl.google.com,Nexuser-ADM
- DOMAIN,mtalk.google.com,Nexuser-ADM

# Internet Service Providers Nexuser-ADM 运营商劫持
- DOMAIN-SUFFIX,17gouwuba.com,Nexuser-ADM
- DOMAIN-SUFFIX,186078.com,Nexuser-ADM
- DOMAIN-SUFFIX,189zj.cn,Nexuser-ADM
- DOMAIN-SUFFIX,285680.com,Nexuser-ADM
- DOMAIN-SUFFIX,3721zh.com,Nexuser-ADM
- DOMAIN-SUFFIX,4336wang.cn,Nexuser-ADM
- DOMAIN-SUFFIX,51chumoping.com,Nexuser-ADM
- DOMAIN-SUFFIX,51mld.cn,Nexuser-ADM
- DOMAIN-SUFFIX,51mypc.cn,Nexuser-ADM
- DOMAIN-SUFFIX,58mingri.cn,Nexuser-ADM
- DOMAIN-SUFFIX,58mingtian.cn,Nexuser-ADM
- DOMAIN-SUFFIX,5vl58stm.com,Nexuser-ADM
- DOMAIN-SUFFIX,6d63d3.com,Nexuser-ADM
- DOMAIN-SUFFIX,7gg.cc,Nexuser-ADM
- DOMAIN-SUFFIX,91veg.com,Nexuser-ADM
- DOMAIN-SUFFIX,9s6q.cn,Nexuser-ADM
- DOMAIN-SUFFIX,adsame.com,Nexuser-ADM
- DOMAIN-SUFFIX,aiclk.com,Nexuser-ADM
- DOMAIN-SUFFIX,akuai.top,Nexuser-ADM
- DOMAIN-SUFFIX,atplay.cn,Nexuser-ADM
- DOMAIN-SUFFIX,baiwanchuangyi.com,Nexuser-ADM
- DOMAIN-SUFFIX,beerto.cn,Nexuser-ADM
- DOMAIN-SUFFIX,beilamusi.com,Nexuser-ADM
- DOMAIN-SUFFIX,benshiw.net,Nexuser-ADM
- DOMAIN-SUFFIX,bianxianmao.com,Nexuser-ADM
- DOMAIN-SUFFIX,bryonypie.com,Nexuser-ADM
- DOMAIN-SUFFIX,cishantao.com,Nexuser-ADM
- DOMAIN-SUFFIX,cszlks.com,Nexuser-ADM
- DOMAIN-SUFFIX,cudaojia.com,Nexuser-ADM
- DOMAIN-SUFFIX,dafapromo.com,Nexuser-ADM
- DOMAIN-SUFFIX,daitdai.com,Nexuser-ADM
- DOMAIN-SUFFIX,dsaeerf.com,Nexuser-ADM
- DOMAIN-SUFFIX,dugesheying.com,Nexuser-ADM
- DOMAIN-SUFFIX,dv8c1t.cn,Nexuser-ADM
- DOMAIN-SUFFIX,echatu.com,Nexuser-ADM
- DOMAIN-SUFFIX,erdoscs.com,Nexuser-ADM
- DOMAIN-SUFFIX,fan-yong.com,Nexuser-ADM
- DOMAIN-SUFFIX,feih.com.cn,Nexuser-ADM
- DOMAIN-SUFFIX,fjlqqc.com,Nexuser-ADM
- DOMAIN-SUFFIX,fkku194.com,Nexuser-ADM
- DOMAIN-SUFFIX,freedrive.cn,Nexuser-ADM
- DOMAIN-SUFFIX,gclick.cn,Nexuser-ADM
- DOMAIN-SUFFIX,goufanli100.com,Nexuser-ADM
- DOMAIN-SUFFIX,goupaoerdai.com,Nexuser-ADM
- DOMAIN-SUFFIX,gouwubang.com,Nexuser-ADM
- DOMAIN-SUFFIX,gzxnlk.com,Nexuser-ADM
- DOMAIN-SUFFIX,haoshengtoys.com,Nexuser-ADM
- DOMAIN-SUFFIX,hyunke.com,Nexuser-ADM
- DOMAIN-SUFFIX,ichaosheng.com,Nexuser-ADM
- DOMAIN-SUFFIX,ishop789.com,Nexuser-ADM
- DOMAIN-SUFFIX,jdkic.com,Nexuser-ADM
- DOMAIN-SUFFIX,jiubuhua.com,Nexuser-ADM
- DOMAIN-SUFFIX,jsncke.com,Nexuser-ADM
- DOMAIN-SUFFIX,junkucm.com,Nexuser-ADM
- DOMAIN-SUFFIX,jwg365.cn,Nexuser-ADM
- DOMAIN-SUFFIX,kawo77.com,Nexuser-ADM
- DOMAIN-SUFFIX,kualianyingxiao.cn,Nexuser-ADM
- DOMAIN-SUFFIX,kumihua.com,Nexuser-ADM
- DOMAIN-SUFFIX,ltheanine.cn,Nexuser-ADM
- DOMAIN-SUFFIX,maipinshangmao.com,Nexuser-ADM
- DOMAIN-SUFFIX,minisplat.cn,Nexuser-ADM
- DOMAIN-SUFFIX,mkitgfs.com,Nexuser-ADM
- DOMAIN-SUFFIX,mlnbike.com,Nexuser-ADM
- DOMAIN-SUFFIX,mobjump.com,Nexuser-ADM
- DOMAIN-SUFFIX,nbkbgd.cn,Nexuser-ADM
- DOMAIN-SUFFIX,newapi.com,Nexuser-ADM
- DOMAIN-SUFFIX,pinzhitmall.com,Nexuser-ADM
- DOMAIN-SUFFIX,poppyta.com,Nexuser-ADM
- DOMAIN-SUFFIX,qianchuanghr.com,Nexuser-ADM
- DOMAIN-SUFFIX,qichexin.com,Nexuser-ADM
- DOMAIN-SUFFIX,qinchugudao.com,Nexuser-ADM
- DOMAIN-SUFFIX,quanliyouxi.cn,Nexuser-ADM
- DOMAIN-SUFFIX,qutaobi.com,Nexuser-ADM
- DOMAIN-SUFFIX,ry51w.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sg536.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifubo.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifuce.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifuda.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifufu.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifuge.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifugu.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifuhe.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifuhu.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifuji.cn,Nexuser-ADM
- DOMAIN-SUFFIX,sifuka.cn,Nexuser-ADM
- DOMAIN-SUFFIX,smgru.net,Nexuser-ADM
- DOMAIN-SUFFIX,taoggou.com,Nexuser-ADM
- DOMAIN-SUFFIX,tcxshop.com,Nexuser-ADM
- DOMAIN-SUFFIX,tjqonline.cn,Nexuser-ADM
- DOMAIN-SUFFIX,topitme.com,Nexuser-ADM
- DOMAIN-SUFFIX,tt3sm4.cn,Nexuser-ADM
- DOMAIN-SUFFIX,tuia.cn,Nexuser-ADM
- DOMAIN-SUFFIX,tuipenguin.com,Nexuser-ADM
- DOMAIN-SUFFIX,tuitiger.com,Nexuser-ADM
- DOMAIN-SUFFIX,websd8.com,Nexuser-ADM
- DOMAIN-SUFFIX,wsgblw.com,Nexuser-ADM
- DOMAIN-SUFFIX,wx16999.com,Nexuser-ADM
- DOMAIN-SUFFIX,xchmai.com,Nexuser-ADM
- DOMAIN-SUFFIX,xiaohuau.xyz,Nexuser-ADM
- DOMAIN-SUFFIX,ygyzx.cn,Nexuser-ADM
- DOMAIN-SUFFIX,yinmong.com,Nexuser-ADM
- DOMAIN-SUFFIX,yitaopt.com,Nexuser-ADM
- DOMAIN-SUFFIX,yjqiqi.com,Nexuser-ADM
- DOMAIN-SUFFIX,yukhj.com,Nexuser-ADM
- DOMAIN-SUFFIX,zhaozecheng.cn,Nexuser-ADM
- DOMAIN-SUFFIX,zhenxinet.com,Nexuser-ADM
- DOMAIN-SUFFIX,zlne800.com,Nexuser-ADM
- DOMAIN-SUFFIX,zunmi.cn,Nexuser-ADM
- DOMAIN-SUFFIX,zzd6.com,Nexuser-ADM
- IP-CIDR,39.107.15.115/32,Nexuser-ADM,no-resolve
- IP-CIDR,47.89.59.182/32,Nexuser-ADM,no-resolve
- IP-CIDR,103.49.209.27/32,Nexuser-ADM,no-resolve
- IP-CIDR,123.56.152.96/32,Nexuser-ADM,no-resolve
# > ChinaTelecom
- IP-CIDR,61.160.200.223/32,Nexuser-ADM,no-resolve
- IP-CIDR,61.160.200.242/32,Nexuser-ADM,no-resolve
- IP-CIDR,61.160.200.252/32,Nexuser-ADM,no-resolve
- IP-CIDR,61.174.50.214/32,Nexuser-ADM,no-resolve
- IP-CIDR,111.175.220.163/32,Nexuser-ADM,no-resolve
- IP-CIDR,111.175.220.164/32,Nexuser-ADM,no-resolve
- IP-CIDR,122.229.8.47/32,Nexuser-ADM,no-resolve
- IP-CIDR,122.229.29.89/32,Nexuser-ADM,no-resolve
- IP-CIDR,124.232.160.178/32,Nexuser-ADM,no-resolve
- IP-CIDR,175.6.223.15/32,Nexuser-ADM,no-resolve
- IP-CIDR,183.59.53.237/32,Nexuser-ADM,no-resolve
- IP-CIDR,218.93.127.37/32,Nexuser-ADM,no-resolve
- IP-CIDR,221.228.17.152/32,Nexuser-ADM,no-resolve
- IP-CIDR,221.231.6.79/32,Nexuser-ADM,no-resolve
- IP-CIDR,222.186.61.91/32,Nexuser-ADM,no-resolve
- IP-CIDR,222.186.61.95/32,Nexuser-ADM,no-resolve
- IP-CIDR,222.186.61.96/32,Nexuser-ADM,no-resolve
- IP-CIDR,222.186.61.97/32,Nexuser-ADM,no-resolve
# > ChinaUnicom
- IP-CIDR,106.75.231.48/32,Nexuser-ADM,no-resolve
- IP-CIDR,119.4.249.166/32,Nexuser-ADM,no-resolve
- IP-CIDR,220.196.52.141/32,Nexuser-ADM,no-resolve
- IP-CIDR,221.6.4.148/32,Nexuser-ADM,no-resolve
# > ChinaMobile
- IP-CIDR,114.247.28.96/32,Nexuser-ADM,no-resolve
- IP-CIDR,221.179.131.72/32,Nexuser-ADM,no-resolve
- IP-CIDR,221.179.140.145/32,Nexuser-ADM,no-resolve
# > Dr.Peng
# - IP-CIDR,10.72.25.0/24,Nexuser-ADM,no-resolve
- IP-CIDR,115.182.16.79/32,Nexuser-ADM,no-resolve
- IP-CIDR,118.144.88.126/32,Nexuser-ADM,no-resolve
- IP-CIDR,118.144.88.215/32,Nexuser-ADM,no-resolve
- IP-CIDR,118.144.88.216/32,Nexuser-ADM,no-resolve
- IP-CIDR,120.76.189.132/32,Nexuser-ADM,no-resolve
- IP-CIDR,124.14.21.147/32,Nexuser-ADM,no-resolve
- IP-CIDR,124.14.21.151/32,Nexuser-ADM,no-resolve
- IP-CIDR,180.166.52.24/32,Nexuser-ADM,no-resolve
- IP-CIDR,211.161.101.106/32,Nexuser-ADM,no-resolve
- IP-CIDR,220.115.251.25/32,Nexuser-ADM,no-resolve
- IP-CIDR,222.73.156.235/32,Nexuser-ADM,no-resolve

# Malware 恶意网站
# > 快压
# https://zhuanlan.zhihu.com/p/39534279
- DOMAIN-SUFFIX,kuaizip.com,Nexuser-ADM
# > MacKeeper
# https://www.lizhi.io/blog/40002904
- DOMAIN-SUFFIX,mackeeper.com,Nexuser-ADM
- DOMAIN-SUFFIX,zryydi.com,Nexuser-ADM
# > Adobe Flash China Special Edition
# https://www.zhihu.com/question/281163698/answer/441388130
- DOMAIN-SUFFIX,flash.cn,Nexuser-ADM
- DOMAIN,geo2.adobe.com,Nexuser-ADM
# > C&J Marketing 思杰马克丁软件
# https://www.zhihu.com/question/46746200
- DOMAIN-SUFFIX,4009997658.com,Nexuser-ADM
- DOMAIN-SUFFIX,abbyychina.com,Nexuser-ADM
- DOMAIN-SUFFIX,bartender.cc,Nexuser-ADM
- DOMAIN-SUFFIX,betterzip.net,Nexuser-ADM
- DOMAIN-SUFFIX,betterzipcn.com,Nexuser-ADM
- DOMAIN-SUFFIX,beyondcompare.cc,Nexuser-ADM
- DOMAIN-SUFFIX,bingdianhuanyuan.cn,Nexuser-ADM
- DOMAIN-SUFFIX,chemdraw.com.cn,Nexuser-ADM
- DOMAIN-SUFFIX,cjmakeding.com,Nexuser-ADM
- DOMAIN-SUFFIX,cjmkt.com,Nexuser-ADM
- DOMAIN-SUFFIX,codesoftchina.com,Nexuser-ADM
- DOMAIN-SUFFIX,coreldrawchina.com,Nexuser-ADM
- DOMAIN-SUFFIX,crossoverchina.com,Nexuser-ADM
- DOMAIN-SUFFIX,dongmansoft.com,Nexuser-ADM
- DOMAIN-SUFFIX,earmasterchina.cn,Nexuser-ADM
- DOMAIN-SUFFIX,easyrecoverychina.com,Nexuser-ADM
- DOMAIN-SUFFIX,ediuschina.com,Nexuser-ADM
- DOMAIN-SUFFIX,flstudiochina.com,Nexuser-ADM
- DOMAIN-SUFFIX,formysql.com,Nexuser-ADM
- DOMAIN-SUFFIX,guitarpro.cc,Nexuser-ADM
- DOMAIN-SUFFIX,huishenghuiying.com.cn,Nexuser-ADM
- DOMAIN-SUFFIX,hypersnap.net,Nexuser-ADM
- DOMAIN-SUFFIX,iconworkshop.cn,Nexuser-ADM
- DOMAIN-SUFFIX,imindmap.cc,Nexuser-ADM
- DOMAIN-SUFFIX,jihehuaban.com.cn,Nexuser-ADM
- DOMAIN-SUFFIX,keyshot.cc,Nexuser-ADM
- DOMAIN-SUFFIX,kingdeecn.cn,Nexuser-ADM
- DOMAIN-SUFFIX,logoshejishi.com,Nexuser-ADM
- DOMAIN-SUFFIX,luping.net.cn,Nexuser-ADM
- DOMAIN-SUFFIX,mairuan.cn,Nexuser-ADM
- DOMAIN-SUFFIX,mairuan.com,Nexuser-ADM
- DOMAIN-SUFFIX,mairuan.com.cn,Nexuser-ADM
- DOMAIN-SUFFIX,mairuan.net,Nexuser-ADM
- DOMAIN-SUFFIX,mairuanwang.com,Nexuser-ADM
- DOMAIN-SUFFIX,makeding.com,Nexuser-ADM
- DOMAIN-SUFFIX,mathtype.cn,Nexuser-ADM
- DOMAIN-SUFFIX,mindmanager.cc,Nexuser-ADM
- DOMAIN-SUFFIX,mindmanager.cn,Nexuser-ADM
- DOMAIN-SUFFIX,mindmapper.cc,Nexuser-ADM
- DOMAIN-SUFFIX,mycleanmymac.com,Nexuser-ADM
- DOMAIN-SUFFIX,nicelabel.cc,Nexuser-ADM
- DOMAIN-SUFFIX,ntfsformac.cc,Nexuser-ADM
- DOMAIN-SUFFIX,ntfsformac.cn,Nexuser-ADM
- DOMAIN-SUFFIX,overturechina.com,Nexuser-ADM
- DOMAIN-SUFFIX,passwordrecovery.cn,Nexuser-ADM
- DOMAIN-SUFFIX,pdfexpert.cc,Nexuser-ADM
- DOMAIN-SUFFIX,photozoomchina.com,Nexuser-ADM
- DOMAIN-SUFFIX,shankejingling.com,Nexuser-ADM
- DOMAIN-SUFFIX,ultraiso.net,Nexuser-ADM
- DOMAIN-SUFFIX,vegaschina.cn,Nexuser-ADM
- DOMAIN-SUFFIX,xmindchina.net,Nexuser-ADM
- DOMAIN-SUFFIX,xshellcn.com,Nexuser-ADM
- DOMAIN-SUFFIX,yihuifu.cn,Nexuser-ADM
- DOMAIN-SUFFIX,yuanchengxiezuo.com,Nexuser-ADM
- DOMAIN-SUFFIX,zbrushcn.com,Nexuser-ADM
- DOMAIN-SUFFIX,zhzzx.com,Nexuser-ADM

# Global Area Network
# (Nexuser-ADM)
# (Music)
# > Deezer
# USER-AGENT,Deezer*,Nexuser-ADM
- DOMAIN-SUFFIX,deezer.com,Nexuser-ADM
- DOMAIN-SUFFIX,dzcdn.net,Nexuser-ADM
# > KKBOX
- DOMAIN-SUFFIX,kkbox.com,Nexuser-ADM
- DOMAIN-SUFFIX,kkbox.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,kfs.io,Nexuser-ADM
# > JOOX
# USER-AGENT,WeMusic*,Nexuser-ADM
# USER-AGENT,JOOX*,Nexuser-ADM
- DOMAIN-SUFFIX,joox.com,Nexuser-ADM
# > Pandora
# USER-AGENT,Pandora*,Nexuser-ADM
- DOMAIN-SUFFIX,pandora.com,Nexuser-ADM
# > SoundCloud
# USER-AGENT,SoundCloud*,Nexuser-ADM
- DOMAIN-SUFFIX,p-cdn.us,Nexuser-ADM
- DOMAIN-SUFFIX,sndcdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,soundcloud.com,Nexuser-ADM
# > Spotify
# USER-AGENT,Spotify*,Nexuser-ADM
- DOMAIN-SUFFIX,pscdn.co,Nexuser-ADM
- DOMAIN-SUFFIX,scdn.co,Nexuser-ADM
- DOMAIN-SUFFIX,spotify.com,Nexuser-ADM
- DOMAIN-SUFFIX,spoti.fi,Nexuser-ADM
- DOMAIN-KEYWORD,spotify.com,Nexuser-ADM
- DOMAIN-KEYWORD,-spotify-com,Nexuser-ADM
# > TIDAL
# USER-AGENT,TIDAL*,Nexuser-ADM
- DOMAIN-SUFFIX,tidal.com,Nexuser-ADM
# > YouTubeMusic
# USER-AGENT,com.google.ios.youtubemusic*,Nexuser-ADM
# USER-AGENT,YouTubeMusic*,Nexuser-ADM
# (Video)
# > All4
# USER-AGENT,All4*,Nexuser-ADM
- DOMAIN-SUFFIX,c4assets.com,Nexuser-ADM
- DOMAIN-SUFFIX,channel4.com,Nexuser-ADM
# > AbemaTV
# USER-AGENT,AbemaTV*,Nexuser-ADM
- DOMAIN-SUFFIX,abema.io,Nexuser-ADM
- DOMAIN-SUFFIX,ameba.jp,Nexuser-ADM
- DOMAIN-SUFFIX,abema.tv,Nexuser-ADM
- DOMAIN-SUFFIX,hayabusa.io,Nexuser-ADM
- DOMAIN,abematv.akamaized.net,Nexuser-ADM
- DOMAIN,ds-linear-abematv.akamaized.net,Nexuser-ADM
- DOMAIN,ds-vod-abematv.akamaized.net,Nexuser-ADM
- DOMAIN,linear-abematv.akamaized.net,Nexuser-ADM
# > Amazon Prime Video
# USER-AGENT,InstantVideo.US*,Nexuser-ADM
# USER-AGENT,Prime%20Video*,Nexuser-ADM
- DOMAIN-SUFFIX,aiv-cdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,aiv-delivery.net,Nexuser-ADM
- DOMAIN-SUFFIX,amazonvideo.com,Nexuser-ADM
- DOMAIN-SUFFIX,primevideo.com,Nexuser-ADM
- DOMAIN,avodmp4s3ww-a.akamaihd.net,Nexuser-ADM
- DOMAIN,d25xi40x97liuc.cloudfront.net,Nexuser-ADM
- DOMAIN,dmqdd6hw24ucf.cloudfront.net,Nexuser-ADM
- DOMAIN,d22qjgkvxw22r6.cloudfront.net,Nexuser-ADM
- DOMAIN,d1v5ir2lpwr8os.cloudfront.net,Nexuser-ADM
- DOMAIN-KEYWORD,avoddashs,Nexuser-ADM
# > Bahamut
# USER-AGENT,Anime*,Nexuser-ADM
- DOMAIN-SUFFIX,bahamut.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,gamer.com.tw,Nexuser-ADM
- DOMAIN,gamer-cds.cdn.hinet.net,Nexuser-ADM
- DOMAIN,gamer2-cds.cdn.hinet.net,Nexuser-ADM
# > BBC iPlayer
# USER-AGENT,BBCiPlayer*,Nexuser-ADM
- DOMAIN-SUFFIX,bbc.co.uk,Nexuser-ADM
- DOMAIN-SUFFIX,bbci.co.uk,Nexuser-ADM
- DOMAIN-KEYWORD,bbcfmt,Nexuser-ADM
- DOMAIN-KEYWORD,uk-live,Nexuser-ADM
# > DAZN
# USER-AGENT,DAZN*,Nexuser-ADM
- DOMAIN-SUFFIX,dazn.com,Nexuser-ADM
- DOMAIN-SUFFIX,dazn-api.com,Nexuser-ADM
- DOMAIN,d151l6v8er5bdm.cloudfront.net,Nexuser-ADM
- DOMAIN-KEYWORD,voddazn,Nexuser-ADM
# > Disney+
# USER-AGENT,Disney+*,Nexuser-ADM
- DOMAIN-SUFFIX,bamgrid.com,Nexuser-ADM
- DOMAIN-SUFFIX,disney-plus.net,Nexuser-ADM
- DOMAIN-SUFFIX,disneyplus.com,Nexuser-ADM
- DOMAIN-SUFFIX,dssott.com,Nexuser-ADM
- DOMAIN,cdn.registerdisney.go.com,Nexuser-ADM
# > encoreTVB
# USER-AGENT,encoreTVB*,Nexuser-ADM
- DOMAIN-SUFFIX,encoretvb.com,Nexuser-ADM
- DOMAIN,edge.api.brightcove.com,Nexuser-ADM
- DOMAIN,bcbolt446c5271-a.akamaihd.net,Nexuser-ADM
# > FOX NOW
# USER-AGENT,FOX%20NOW*,Nexuser-ADM
- DOMAIN-SUFFIX,fox.com,Nexuser-ADM
- DOMAIN-SUFFIX,foxdcg.com,Nexuser-ADM
- DOMAIN-SUFFIX,theplatform.com,Nexuser-ADM
- DOMAIN-SUFFIX,uplynk.com,Nexuser-ADM
# > HBO NOW
# USER-AGENT,HBO%20NOW*,Nexuser-ADM
- DOMAIN-SUFFIX,hbo.com,Nexuser-ADM
- DOMAIN-SUFFIX,hbogo.com,Nexuser-ADM
- DOMAIN-SUFFIX,hbonow.com,Nexuser-ADM
# > HBO GO HKG
# USER-AGENT,HBO%20GO%20PROD%20HKG*,Nexuser-ADM
- DOMAIN-SUFFIX,hbogoasia.com,Nexuser-ADM
- DOMAIN-SUFFIX,hbogoasia.hk,Nexuser-ADM
- DOMAIN,bcbolthboa-a.akamaihd.net,Nexuser-ADM
- DOMAIN,players.brightcove.net,Nexuser-ADM
- DOMAIN,s3-ap-southeast-1.amazonaws.com,Nexuser-ADM
- DOMAIN,dai3fd1oh325y.cloudfront.net,Nexuser-ADM
- DOMAIN,44wilhpljf.execute-api.ap-southeast-1.amazonaws.com,Nexuser-ADM
- DOMAIN,hboasia1-i.akamaihd.net,Nexuser-ADM
- DOMAIN,hboasia2-i.akamaihd.net,Nexuser-ADM
- DOMAIN,hboasia3-i.akamaihd.net,Nexuser-ADM
- DOMAIN,hboasia4-i.akamaihd.net,Nexuser-ADM
- DOMAIN,hboasia5-i.akamaihd.net,Nexuser-ADM
- DOMAIN,cf-images.ap-southeast-1.prod.boltdns.net,Nexuser-ADM
# > 华文电视
# USER-AGENT,HWTVMobile*,Nexuser-ADM
- DOMAIN-SUFFIX,5itv.tv,Nexuser-ADM
- DOMAIN-SUFFIX,ocnttv.com,Nexuser-ADM
# > Hulu
- DOMAIN-SUFFIX,hulu.com,Nexuser-ADM
- DOMAIN-SUFFIX,huluim.com,Nexuser-ADM
- DOMAIN-SUFFIX,hulustream.com,Nexuser-ADM
# > Hulu(フールー)
- DOMAIN-SUFFIX,happyon.jp,Nexuser-ADM
- DOMAIN-SUFFIX,hulu.jp,Nexuser-ADM
# > ITV
# USER-AGENT,ITV_Player*,Nexuser-ADM
- DOMAIN-SUFFIX,itv.com,Nexuser-ADM
- DOMAIN-SUFFIX,itvstatic.com,Nexuser-ADM
- DOMAIN,itvpnpmobile-a.akamaihd.net,Nexuser-ADM
# > KKTV
# USER-AGENT,KKTV*,Nexuser-ADM
# USER-AGENT,com.kktv.ios.kktv*,Nexuser-ADM
- DOMAIN-SUFFIX,kktv.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,kktv.me,Nexuser-ADM
- DOMAIN,kktv-theater.kk.stream,Nexuser-ADM
# > Line TV
# USER-AGENT,LINE%20TV*,Nexuser-ADM
- DOMAIN-SUFFIX,linetv.tw,Nexuser-ADM
- DOMAIN,d3c7rimkq79yfu.cloudfront.net,Nexuser-ADM
# > LiTV
- DOMAIN-SUFFIX,litv.tv,Nexuser-ADM
- DOMAIN,litvfreemobile-hichannel.cdn.hinet.net,Nexuser-ADM
# > My5
# USER-AGENT,My5*,Nexuser-ADM
- DOMAIN-SUFFIX,channel5.com,Nexuser-ADM
- DOMAIN-SUFFIX,my5.tv,Nexuser-ADM
- DOMAIN,d349g9zuie06uo.cloudfront.net,Nexuser-ADM
# > myTV SUPER
# USER-AGENT,mytv*,Nexuser-ADM
- DOMAIN-SUFFIX,mytvsuper.com,Nexuser-ADM
- DOMAIN-SUFFIX,tvb.com,Nexuser-ADM
# > Netflix
# USER-AGENT,Argo*,Nexuser-ADM
- DOMAIN-SUFFIX,netflix.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflix.net,Nexuser-ADM
- DOMAIN-SUFFIX,nflxext.com,Nexuser-ADM
- DOMAIN-SUFFIX,nflximg.com,Nexuser-ADM
- DOMAIN-SUFFIX,nflximg.net,Nexuser-ADM
- DOMAIN-SUFFIX,nflxso.net,Nexuser-ADM
- DOMAIN-SUFFIX,nflxvideo.net,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest0.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest1.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest2.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest3.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest4.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest5.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest6.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest7.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest8.com,Nexuser-ADM
- DOMAIN-SUFFIX,netflixdnstest9.com,Nexuser-ADM
- IP-CIDR,23.246.0.0/18,Nexuser-ADM,no-resolve
- IP-CIDR,37.77.184.0/21,Nexuser-ADM,no-resolve
- IP-CIDR,45.57.0.0/17,Nexuser-ADM,no-resolve
- IP-CIDR,64.120.128.0/17,Nexuser-ADM,no-resolve
- IP-CIDR,66.197.128.0/17,Nexuser-ADM,no-resolve
- IP-CIDR,108.175.32.0/20,Nexuser-ADM,no-resolve
- IP-CIDR,192.173.64.0/18,Nexuser-ADM,no-resolve
- IP-CIDR,198.38.96.0/19,Nexuser-ADM,no-resolve
- IP-CIDR,198.45.48.0/20,Nexuser-ADM,no-resolve
# > niconico
# USER-AGENT,Niconico*,Nexuser-ADM
- DOMAIN-SUFFIX,dmc.nico,Nexuser-ADM
- DOMAIN-SUFFIX,nicovideo.jp,Nexuser-ADM
- DOMAIN-SUFFIX,nimg.jp,Nexuser-ADM
- DOMAIN-SUFFIX,socdm.com,Nexuser-ADM
# > PBS
# USER-AGENT,PBS*,Nexuser-ADM
- DOMAIN-SUFFIX,pbs.org,Nexuser-ADM
# > Pornhub
- DOMAIN-SUFFIX,phncdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,pornhub.com,Nexuser-ADM
- DOMAIN-SUFFIX,pornhubpremium.com,Nexuser-ADM
# > 台湾好
# USER-AGENT,TaiwanGood*,Nexuser-ADM
- DOMAIN-SUFFIX,skyking.com.tw,Nexuser-ADM
- DOMAIN,hamifans.emome.net,Nexuser-ADM
# > Twitch
- DOMAIN-SUFFIX,twitch.tv,Nexuser-ADM
- DOMAIN-SUFFIX,twitchcdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,ttvnw.net,Nexuser-ADM
- DOMAIN-SUFFIX,jtvnw.net,Nexuser-ADM
# > ViuTV
# USER-AGENT,Viu*,Nexuser-ADM
# USER-AGENT,ViuTV*,Nexuser-ADM
- DOMAIN-SUFFIX,viu.com,Nexuser-ADM
- DOMAIN-SUFFIX,viu.tv,Nexuser-ADM
- DOMAIN,api.viu.now.com,Nexuser-ADM
- DOMAIN,d1k2us671qcoau.cloudfront.net,Nexuser-ADM
- DOMAIN,d2anahhhmp1ffz.cloudfront.net,Nexuser-ADM
- DOMAIN,dfp6rglgjqszk.cloudfront.net,Nexuser-ADM
# > YouTube
# USER-AGENT,com.google.ios.youtube*,Nexuser-ADM
# USER-AGENT,YouTube*,Nexuser-ADM
- DOMAIN-SUFFIX,googlevideo.com,Nexuser-ADM
- DOMAIN-SUFFIX,youtube.com,Nexuser-ADM
- DOMAIN,youtubei.googleapis.com,Nexuser-ADM

# (Nexuser-ADM)
# > 愛奇藝台灣站
- DOMAIN,cache.video.iqiyi.com,Nexuser-ADM
# > bilibili
- DOMAIN-SUFFIX,bilibili.com,Nexuser-ADM
- DOMAIN,upos-hz-mirrorakam.akamaized.net,Nexuser-ADM

# (DNS Cache Pollution Protection)
# > Google
- DOMAIN-SUFFIX,ampproject.org,Nexuser-ADM
- DOMAIN-SUFFIX,appspot.com,Nexuser-ADM
- DOMAIN-SUFFIX,blogger.com,Nexuser-ADM
- DOMAIN-SUFFIX,getoutline.org,Nexuser-ADM
- DOMAIN-SUFFIX,gvt0.com,Nexuser-ADM
- DOMAIN-SUFFIX,gvt1.com,Nexuser-ADM
- DOMAIN-SUFFIX,gvt3.com,Nexuser-ADM
- DOMAIN-SUFFIX,xn--ngstr-lra8j.com,Nexuser-ADM
- DOMAIN-KEYWORD,google,Nexuser-ADM
- DOMAIN-KEYWORD,blogspot,Nexuser-ADM
# > Microsoft
- DOMAIN-SUFFIX,onedrive.live.com,Nexuser-ADM
- DOMAIN-SUFFIX,xboxlive.com,Nexuser-ADM
# > Facebook
- DOMAIN-SUFFIX,cdninstagram.com,Nexuser-ADM
- DOMAIN-SUFFIX,fb.com,Nexuser-ADM
- DOMAIN-SUFFIX,fb.me,Nexuser-ADM
- DOMAIN-SUFFIX,fbaddins.com,Nexuser-ADM
- DOMAIN-SUFFIX,fbcdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,fbsbx.com,Nexuser-ADM
- DOMAIN-SUFFIX,fbworkmail.com,Nexuser-ADM
- DOMAIN-SUFFIX,instagram.com,Nexuser-ADM
- DOMAIN-SUFFIX,m.me,Nexuser-ADM
- DOMAIN-SUFFIX,messenger.com,Nexuser-ADM
- DOMAIN-SUFFIX,oculus.com,Nexuser-ADM
- DOMAIN-SUFFIX,oculuscdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,rocksdb.org,Nexuser-ADM
- DOMAIN-SUFFIX,whatsapp.com,Nexuser-ADM
- DOMAIN-SUFFIX,whatsapp.net,Nexuser-ADM
- DOMAIN-KEYWORD,facebook,Nexuser-ADM
- IP-CIDR,3.123.36.126/32,Nexuser-ADM,no-resolve
- IP-CIDR,35.157.215.84/32,Nexuser-ADM,no-resolve
- IP-CIDR,35.157.217.255/32,Nexuser-ADM,no-resolve
- IP-CIDR,52.58.209.134/32,Nexuser-ADM,no-resolve
- IP-CIDR,54.93.124.31/32,Nexuser-ADM,no-resolve
- IP-CIDR,54.162.243.80/32,Nexuser-ADM,no-resolve
- IP-CIDR,54.173.34.141/32,Nexuser-ADM,no-resolve
- IP-CIDR,54.235.23.242/32,Nexuser-ADM,no-resolve
- IP-CIDR,169.45.248.118/32,Nexuser-ADM,no-resolve
# > Twitter
- DOMAIN-SUFFIX,pscp.tv,Nexuser-ADM
- DOMAIN-SUFFIX,periscope.tv,Nexuser-ADM
- DOMAIN-SUFFIX,t.co,Nexuser-ADM
- DOMAIN-SUFFIX,twimg.co,Nexuser-ADM
- DOMAIN-SUFFIX,twimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,twitpic.com,Nexuser-ADM
- DOMAIN-SUFFIX,vine.co,Nexuser-ADM
- DOMAIN-KEYWORD,twitter,Nexuser-ADM
# > Telegram
- DOMAIN-SUFFIX,t.me,Nexuser-ADM
- DOMAIN-SUFFIX,tdesktop.com,Nexuser-ADM
- DOMAIN-SUFFIX,telegra.ph,Nexuser-ADM
- DOMAIN-SUFFIX,telegram.me,Nexuser-ADM
- DOMAIN-SUFFIX,telegram.org,Nexuser-ADM
- IP-CIDR,91.108.4.0/22,Nexuser-ADM,no-resolve
- IP-CIDR,91.108.8.0/22,Nexuser-ADM,no-resolve
- IP-CIDR,91.108.12.0/22,Nexuser-ADM,no-resolve
- IP-CIDR,91.108.16.0/22,Nexuser-ADM,no-resolve
- IP-CIDR,91.108.56.0/22,Nexuser-ADM,no-resolve
- IP-CIDR,149.154.160.0/20,Nexuser-ADM,no-resolve
# > Line
- DOMAIN-SUFFIX,line.me,Nexuser-ADM
- DOMAIN-SUFFIX,line-apps.com,Nexuser-ADM
- DOMAIN-SUFFIX,line-scdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,naver.jp,Nexuser-ADM
- IP-CIDR,103.2.30.0/23,Nexuser-ADM,no-resolve
- IP-CIDR,125.209.208.0/20,Nexuser-ADM,no-resolve
- IP-CIDR,147.92.128.0/17,Nexuser-ADM,no-resolve
- IP-CIDR,203.104.144.0/21,Nexuser-ADM,no-resolve
# > Other
- DOMAIN-SUFFIX,4shared.com,Nexuser-ADM
- DOMAIN-SUFFIX,520cc.cc,Nexuser-ADM
- DOMAIN-SUFFIX,881903.com,Nexuser-ADM
- DOMAIN-SUFFIX,9cache.com,Nexuser-ADM
- DOMAIN-SUFFIX,9gag.com,Nexuser-ADM
- DOMAIN-SUFFIX,abc.com,Nexuser-ADM
- DOMAIN-SUFFIX,abc.net.au,Nexuser-ADM
- DOMAIN-SUFFIX,abebooks.com,Nexuser-ADM
- DOMAIN-SUFFIX,amazon.co.jp,Nexuser-ADM
- DOMAIN-SUFFIX,apigee.com,Nexuser-ADM
- DOMAIN-SUFFIX,apk-dl.com,Nexuser-ADM
- DOMAIN-SUFFIX,apkfind.com,Nexuser-ADM
- DOMAIN-SUFFIX,apkmirror.com,Nexuser-ADM
- DOMAIN-SUFFIX,apkmonk.com,Nexuser-ADM
- DOMAIN-SUFFIX,apkpure.com,Nexuser-ADM
- DOMAIN-SUFFIX,aptoide.com,Nexuser-ADM
- DOMAIN-SUFFIX,archive.is,Nexuser-ADM
- DOMAIN-SUFFIX,archive.org,Nexuser-ADM
- DOMAIN-SUFFIX,arte.tv,Nexuser-ADM
- DOMAIN-SUFFIX,artstation.com,Nexuser-ADM
- DOMAIN-SUFFIX,arukas.io,Nexuser-ADM
- DOMAIN-SUFFIX,ask.com,Nexuser-ADM
- DOMAIN-SUFFIX,avg.com,Nexuser-ADM
- DOMAIN-SUFFIX,avgle.com,Nexuser-ADM
- DOMAIN-SUFFIX,badoo.com,Nexuser-ADM
- DOMAIN-SUFFIX,bandwagonhost.com,Nexuser-ADM
- DOMAIN-SUFFIX,bbc.com,Nexuser-ADM
- DOMAIN-SUFFIX,behance.net,Nexuser-ADM
- DOMAIN-SUFFIX,bibox.com,Nexuser-ADM
- DOMAIN-SUFFIX,biggo.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,binance.com,Nexuser-ADM
- DOMAIN-SUFFIX,bitcointalk.org,Nexuser-ADM
- DOMAIN-SUFFIX,bitfinex.com,Nexuser-ADM
- DOMAIN-SUFFIX,bitmex.com,Nexuser-ADM
- DOMAIN-SUFFIX,bit-z.com,Nexuser-ADM
- DOMAIN-SUFFIX,bloglovin.com,Nexuser-ADM
- DOMAIN-SUFFIX,bloomberg.cn,Nexuser-ADM
- DOMAIN-SUFFIX,bloomberg.com,Nexuser-ADM
- DOMAIN-SUFFIX,blubrry.com,Nexuser-ADM
- DOMAIN-SUFFIX,book.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,booklive.jp,Nexuser-ADM
- DOMAIN-SUFFIX,books.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,boslife.net,Nexuser-ADM
- DOMAIN-SUFFIX,box.com,Nexuser-ADM
- DOMAIN-SUFFIX,businessinsider.com,Nexuser-ADM
- DOMAIN-SUFFIX,bwh1.net,Nexuser-ADM
- DOMAIN-SUFFIX,castbox.fm,Nexuser-ADM
- DOMAIN-SUFFIX,cbc.ca,Nexuser-ADM
- DOMAIN-SUFFIX,cdw.com,Nexuser-ADM
- DOMAIN-SUFFIX,change.org,Nexuser-ADM
- DOMAIN-SUFFIX,channelnewsasia.com,Nexuser-ADM
- DOMAIN-SUFFIX,ck101.com,Nexuser-ADM
- DOMAIN-SUFFIX,clarionproject.org,Nexuser-ADM
- DOMAIN-SUFFIX,clyp.it,Nexuser-ADM
- DOMAIN-SUFFIX,cna.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,comparitech.com,Nexuser-ADM
- DOMAIN-SUFFIX,conoha.jp,Nexuser-ADM
- DOMAIN-SUFFIX,crucial.com,Nexuser-ADM
- DOMAIN-SUFFIX,cts.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,cw.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,cyberctm.com,Nexuser-ADM
- DOMAIN-SUFFIX,dailymotion.com,Nexuser-ADM
- DOMAIN-SUFFIX,dailyview.tw,Nexuser-ADM
- DOMAIN-SUFFIX,daum.net,Nexuser-ADM
- DOMAIN-SUFFIX,daumcdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,dcard.tw,Nexuser-ADM
- DOMAIN-SUFFIX,deepdiscount.com,Nexuser-ADM
- DOMAIN-SUFFIX,depositphotos.com,Nexuser-ADM
- DOMAIN-SUFFIX,deviantart.com,Nexuser-ADM
- DOMAIN-SUFFIX,disconnect.me,Nexuser-ADM
- DOMAIN-SUFFIX,discordapp.com,Nexuser-ADM
- DOMAIN-SUFFIX,discordapp.net,Nexuser-ADM
- DOMAIN-SUFFIX,disqus.com,Nexuser-ADM
- DOMAIN-SUFFIX,dlercloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,dns2go.com,Nexuser-ADM
- DOMAIN-SUFFIX,dowjones.com,Nexuser-ADM
- DOMAIN-SUFFIX,dropbox.com,Nexuser-ADM
- DOMAIN-SUFFIX,dropboxusercontent.com,Nexuser-ADM
- DOMAIN-SUFFIX,duckduckgo.com,Nexuser-ADM
- DOMAIN-SUFFIX,dw.com,Nexuser-ADM
- DOMAIN-SUFFIX,dynu.com,Nexuser-ADM
- DOMAIN-SUFFIX,earthcam.com,Nexuser-ADM
- DOMAIN-SUFFIX,ebookservice.tw,Nexuser-ADM
- DOMAIN-SUFFIX,economist.com,Nexuser-ADM
- DOMAIN-SUFFIX,edgecastcdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,edu,Nexuser-ADM
- DOMAIN-SUFFIX,elpais.com,Nexuser-ADM
- DOMAIN-SUFFIX,enanyang.my,Nexuser-ADM
- DOMAIN-SUFFIX,encyclopedia.com,Nexuser-ADM
- DOMAIN-SUFFIX,esoir.be,Nexuser-ADM
- DOMAIN-SUFFIX,etherscan.io,Nexuser-ADM
- DOMAIN-SUFFIX,euronews.com,Nexuser-ADM
- DOMAIN-SUFFIX,evozi.com,Nexuser-ADM
- DOMAIN-SUFFIX,feedly.com,Nexuser-ADM
- DOMAIN-SUFFIX,firech.at,Nexuser-ADM
- DOMAIN-SUFFIX,flickr.com,Nexuser-ADM
- DOMAIN-SUFFIX,flitto.com,Nexuser-ADM
- DOMAIN-SUFFIX,foreignpolicy.com,Nexuser-ADM
- DOMAIN-SUFFIX,freebrowser.org,Nexuser-ADM
- DOMAIN-SUFFIX,freewechat.com,Nexuser-ADM
- DOMAIN-SUFFIX,freeweibo.com,Nexuser-ADM
- DOMAIN-SUFFIX,friday.tw,Nexuser-ADM
- DOMAIN-SUFFIX,ftchinese.com,Nexuser-ADM
- DOMAIN-SUFFIX,ftimg.net,Nexuser-ADM
- DOMAIN-SUFFIX,gate.io,Nexuser-ADM
- DOMAIN-SUFFIX,getlantern.org,Nexuser-ADM
- DOMAIN-SUFFIX,getsync.com,Nexuser-ADM
- DOMAIN-SUFFIX,globalvoices.org,Nexuser-ADM
- DOMAIN-SUFFIX,goo.ne.jp,Nexuser-ADM
- DOMAIN-SUFFIX,goodreads.com,Nexuser-ADM
- DOMAIN-SUFFIX,gov,Nexuser-ADM
- DOMAIN-SUFFIX,gov.tw,Nexuser-ADM
- DOMAIN-SUFFIX,greatfire.org,Nexuser-ADM
- DOMAIN-SUFFIX,gumroad.com,Nexuser-ADM
- DOMAIN-SUFFIX,hbg.com,Nexuser-ADM
- DOMAIN-SUFFIX,heroku.com,Nexuser-ADM
- DOMAIN-SUFFIX,hightail.com,Nexuser-ADM
- DOMAIN-SUFFIX,hk01.com,Nexuser-ADM
- DOMAIN-SUFFIX,hkbf.org,Nexuser-ADM
- DOMAIN-SUFFIX,hkbookcity.com,Nexuser-ADM
- DOMAIN-SUFFIX,hkej.com,Nexuser-ADM
- DOMAIN-SUFFIX,hket.com,Nexuser-ADM
- DOMAIN-SUFFIX,hkgolden.com,Nexuser-ADM
- DOMAIN-SUFFIX,hootsuite.com,Nexuser-ADM
- DOMAIN-SUFFIX,hudson.org,Nexuser-ADM
- DOMAIN-SUFFIX,hyread.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,ibtimes.com,Nexuser-ADM
- DOMAIN-SUFFIX,i-cable.com,Nexuser-ADM
- DOMAIN-SUFFIX,icij.org,Nexuser-ADM
- DOMAIN-SUFFIX,icoco.com,Nexuser-ADM
- DOMAIN-SUFFIX,imgur.com,Nexuser-ADM
- DOMAIN-SUFFIX,initiummall.com,Nexuser-ADM
- DOMAIN-SUFFIX,insecam.org,Nexuser-ADM
- DOMAIN-SUFFIX,ipfs.io,Nexuser-ADM
- DOMAIN-SUFFIX,issuu.com,Nexuser-ADM
- DOMAIN-SUFFIX,istockphoto.com,Nexuser-ADM
- DOMAIN-SUFFIX,japantimes.co.jp,Nexuser-ADM
- DOMAIN-SUFFIX,jiji.com,Nexuser-ADM
- DOMAIN-SUFFIX,jinx.com,Nexuser-ADM
- DOMAIN-SUFFIX,jkforum.net,Nexuser-ADM
- DOMAIN-SUFFIX,joinmastodon.org,Nexuser-ADM
- DOMAIN-SUFFIX,justmysocks.net,Nexuser-ADM
- DOMAIN-SUFFIX,justpaste.it,Nexuser-ADM
- DOMAIN-SUFFIX,kakao.com,Nexuser-ADM
- DOMAIN-SUFFIX,kakaocorp.com,Nexuser-ADM
- DOMAIN-SUFFIX,kik.com,Nexuser-ADM
- DOMAIN-SUFFIX,kobo.com,Nexuser-ADM
- DOMAIN-SUFFIX,kobobooks.com,Nexuser-ADM
- DOMAIN-SUFFIX,kodingen.com,Nexuser-ADM
- DOMAIN-SUFFIX,lemonde.fr,Nexuser-ADM
- DOMAIN-SUFFIX,lepoint.fr,Nexuser-ADM
- DOMAIN-SUFFIX,lihkg.com,Nexuser-ADM
- DOMAIN-SUFFIX,listennotes.com,Nexuser-ADM
- DOMAIN-SUFFIX,livestream.com,Nexuser-ADM
- DOMAIN-SUFFIX,logmein.com,Nexuser-ADM
- DOMAIN-SUFFIX,mail.ru,Nexuser-ADM
- DOMAIN-SUFFIX,mailchimp.com,Nexuser-ADM
- DOMAIN-SUFFIX,marc.info,Nexuser-ADM
- DOMAIN-SUFFIX,matters.news,Nexuser-ADM
- DOMAIN-SUFFIX,maying.co,Nexuser-ADM
- DOMAIN-SUFFIX,medium.com,Nexuser-ADM
- DOMAIN-SUFFIX,mega.nz,Nexuser-ADM
- DOMAIN-SUFFIX,mil,Nexuser-ADM
- DOMAIN-SUFFIX,mingpao.com,Nexuser-ADM
- DOMAIN-SUFFIX,mobile01.com,Nexuser-ADM
- DOMAIN-SUFFIX,myspace.com,Nexuser-ADM
- DOMAIN-SUFFIX,myspacecdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,nanyang.com,Nexuser-ADM
- DOMAIN-SUFFIX,naver.com,Nexuser-ADM
- DOMAIN-SUFFIX,neowin.net,Nexuser-ADM
- DOMAIN-SUFFIX,newstapa.org,Nexuser-ADM
- DOMAIN-SUFFIX,nexitally.com,Nexuser-ADM
- DOMAIN-SUFFIX,nhk.or.jp,Nexuser-ADM
- DOMAIN-SUFFIX,nicovideo.jp,Nexuser-ADM
- DOMAIN-SUFFIX,nii.ac.jp,Nexuser-ADM
- DOMAIN-SUFFIX,nikkei.com,Nexuser-ADM
- DOMAIN-SUFFIX,nofile.io,Nexuser-ADM
- DOMAIN-SUFFIX,now.com,Nexuser-ADM
- DOMAIN-SUFFIX,nrk.no,Nexuser-ADM
- DOMAIN-SUFFIX,nyt.com,Nexuser-ADM
- DOMAIN-SUFFIX,nytchina.com,Nexuser-ADM
- DOMAIN-SUFFIX,nytcn.me,Nexuser-ADM
- DOMAIN-SUFFIX,nytco.com,Nexuser-ADM
- DOMAIN-SUFFIX,nytimes.com,Nexuser-ADM
- DOMAIN-SUFFIX,nytimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,nytlog.com,Nexuser-ADM
- DOMAIN-SUFFIX,nytstyle.com,Nexuser-ADM
- DOMAIN-SUFFIX,ok.ru,Nexuser-ADM
- DOMAIN-SUFFIX,okex.com,Nexuser-ADM
- DOMAIN-SUFFIX,on.cc,Nexuser-ADM
- DOMAIN-SUFFIX,orientaldaily.com.my,Nexuser-ADM
- DOMAIN-SUFFIX,overcast.fm,Nexuser-ADM
- DOMAIN-SUFFIX,paltalk.com,Nexuser-ADM
- DOMAIN-SUFFIX,pao-pao.net,Nexuser-ADM
- DOMAIN-SUFFIX,parsevideo.com,Nexuser-ADM
- DOMAIN-SUFFIX,pbxes.com,Nexuser-ADM
- DOMAIN-SUFFIX,pcdvd.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,pchome.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,pcloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,picacomic.com,Nexuser-ADM
- DOMAIN-SUFFIX,pinimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,pixiv.net,Nexuser-ADM
- DOMAIN-SUFFIX,player.fm,Nexuser-ADM
- DOMAIN-SUFFIX,plurk.com,Nexuser-ADM
- DOMAIN-SUFFIX,po18.tw,Nexuser-ADM
- DOMAIN-SUFFIX,potato.im,Nexuser-ADM
- DOMAIN-SUFFIX,potatso.com,Nexuser-ADM
- DOMAIN-SUFFIX,prism-break.org,Nexuser-ADM
- DOMAIN-SUFFIX,proxifier.com,Nexuser-ADM
- DOMAIN-SUFFIX,pt.im,Nexuser-ADM
- DOMAIN-SUFFIX,pts.org.tw,Nexuser-ADM
- DOMAIN-SUFFIX,pubu.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,pubu.tw,Nexuser-ADM
- DOMAIN-SUFFIX,pureapk.com,Nexuser-ADM
- DOMAIN-SUFFIX,quora.com,Nexuser-ADM
- DOMAIN-SUFFIX,quoracdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,rakuten.co.jp,Nexuser-ADM
- DOMAIN-SUFFIX,readingtimes.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,readmoo.com,Nexuser-ADM
- DOMAIN-SUFFIX,redbubble.com,Nexuser-ADM
- DOMAIN-SUFFIX,reddit.com,Nexuser-ADM
- DOMAIN-SUFFIX,redditmedia.com,Nexuser-ADM
- DOMAIN-SUFFIX,resilio.com,Nexuser-ADM
- DOMAIN-SUFFIX,reuters.com,Nexuser-ADM
- DOMAIN-SUFFIX,reutersmedia.net,Nexuser-ADM
- DOMAIN-SUFFIX,rfi.fr,Nexuser-ADM
- DOMAIN-SUFFIX,rixcloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,roadshow.hk,Nexuser-ADM
- DOMAIN-SUFFIX,scmp.com,Nexuser-ADM
- DOMAIN-SUFFIX,scribd.com,Nexuser-ADM
- DOMAIN-SUFFIX,seatguru.com,Nexuser-ADM
- DOMAIN-SUFFIX,shadowsocks.org,Nexuser-ADM
- DOMAIN-SUFFIX,shopee.tw,Nexuser-ADM
- DOMAIN-SUFFIX,slideshare.net,Nexuser-ADM
- DOMAIN-SUFFIX,softfamous.com,Nexuser-ADM
- DOMAIN-SUFFIX,soundcloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,ssrcloud.org,Nexuser-ADM
- DOMAIN-SUFFIX,startpage.com,Nexuser-ADM
- DOMAIN-SUFFIX,steamcommunity.com,Nexuser-ADM
- DOMAIN-SUFFIX,steemit.com,Nexuser-ADM
- DOMAIN-SUFFIX,steemitwallet.com,Nexuser-ADM
- DOMAIN-SUFFIX,t66y.com,Nexuser-ADM
- DOMAIN-SUFFIX,tapatalk.com,Nexuser-ADM
- DOMAIN-SUFFIX,teco-hk.org,Nexuser-ADM
- DOMAIN-SUFFIX,teco-mo.org,Nexuser-ADM
- DOMAIN-SUFFIX,teddysun.com,Nexuser-ADM
- DOMAIN-SUFFIX,textnow.me,Nexuser-ADM
- DOMAIN-SUFFIX,theguardian.com,Nexuser-ADM
- DOMAIN-SUFFIX,theinitium.com,Nexuser-ADM
- DOMAIN-SUFFIX,thetvdb.com,Nexuser-ADM
- DOMAIN-SUFFIX,tineye.com,Nexuser-ADM
- DOMAIN-SUFFIX,torproject.org,Nexuser-ADM
- DOMAIN-SUFFIX,tumblr.com,Nexuser-ADM
- DOMAIN-SUFFIX,turbobit.net,Nexuser-ADM
- DOMAIN-SUFFIX,tutanota.com,Nexuser-ADM
- DOMAIN-SUFFIX,tvboxnow.com,Nexuser-ADM
- DOMAIN-SUFFIX,udn.com,Nexuser-ADM
- DOMAIN-SUFFIX,unseen.is,Nexuser-ADM
- DOMAIN-SUFFIX,upmedia.mg,Nexuser-ADM
- DOMAIN-SUFFIX,uptodown.com,Nexuser-ADM
- DOMAIN-SUFFIX,urbandictionary.com,Nexuser-ADM
- DOMAIN-SUFFIX,ustream.tv,Nexuser-ADM
- DOMAIN-SUFFIX,uwants.com,Nexuser-ADM
- DOMAIN-SUFFIX,v2ray.com,Nexuser-ADM
- DOMAIN-SUFFIX,viber.com,Nexuser-ADM
- DOMAIN-SUFFIX,videopress.com,Nexuser-ADM
- DOMAIN-SUFFIX,vimeo.com,Nexuser-ADM
- DOMAIN-SUFFIX,voachinese.com,Nexuser-ADM
- DOMAIN-SUFFIX,voanews.com,Nexuser-ADM
- DOMAIN-SUFFIX,voxer.com,Nexuser-ADM
- DOMAIN-SUFFIX,vzw.com,Nexuser-ADM
- DOMAIN-SUFFIX,w3schools.com,Nexuser-ADM
- DOMAIN-SUFFIX,washingtonpost.com,Nexuser-ADM
- DOMAIN-SUFFIX,wattpad.com,Nexuser-ADM
- DOMAIN-SUFFIX,whoer.net,Nexuser-ADM
- DOMAIN-SUFFIX,wikimapia.org,Nexuser-ADM
- DOMAIN-SUFFIX,wikipedia.org,Nexuser-ADM
- DOMAIN-SUFFIX,wikiquote.org,Nexuser-ADM
- DOMAIN-SUFFIX,wikiwand.com,Nexuser-ADM
- DOMAIN-SUFFIX,winudf.com,Nexuser-ADM
- DOMAIN-SUFFIX,wire.com,Nexuser-ADM
- DOMAIN-SUFFIX,wordpress.com,Nexuser-ADM
- DOMAIN-SUFFIX,workflow.is,Nexuser-ADM
- DOMAIN-SUFFIX,worldcat.org,Nexuser-ADM
- DOMAIN-SUFFIX,wsj.com,Nexuser-ADM
- DOMAIN-SUFFIX,wsj.net,Nexuser-ADM
- DOMAIN-SUFFIX,xhamster.com,Nexuser-ADM
- DOMAIN-SUFFIX,xn--90wwvt03e.com,Nexuser-ADM
- DOMAIN-SUFFIX,xn--i2ru8q2qg.com,Nexuser-ADM
- DOMAIN-SUFFIX,xnxx.com,Nexuser-ADM
- DOMAIN-SUFFIX,xvideos.com,Nexuser-ADM
- DOMAIN-SUFFIX,yahoo.com,Nexuser-ADM
- DOMAIN-SUFFIX,yandex.ru,Nexuser-ADM
- DOMAIN-SUFFIX,ycombinator.com,Nexuser-ADM
- DOMAIN-SUFFIX,yesasia.com,Nexuser-ADM
- DOMAIN-SUFFIX,yes-news.com,Nexuser-ADM
- DOMAIN-SUFFIX,yomiuri.co.jp,Nexuser-ADM
- DOMAIN-SUFFIX,you-get.org,Nexuser-ADM
- DOMAIN-SUFFIX,zaobao.com,Nexuser-ADM
- DOMAIN-SUFFIX,zb.com,Nexuser-ADM
- DOMAIN-SUFFIX,zello.com,Nexuser-ADM
- DOMAIN-SUFFIX,zeronet.io,Nexuser-ADM
- DOMAIN-SUFFIX,zoom.us,Nexuser-ADM
- DOMAIN-KEYWORD,github,Nexuser-ADM
- DOMAIN-KEYWORD,jav,Nexuser-ADM
- DOMAIN-KEYWORD,pinterest,Nexuser-ADM
- DOMAIN-KEYWORD,porn,Nexuser-ADM
- DOMAIN-KEYWORD,wikileaks,Nexuser-ADM

# (Region-Restricted Access Denied)
- DOMAIN-SUFFIX,apartmentratings.com,Nexuser-ADM
- DOMAIN-SUFFIX,apartments.com,Nexuser-ADM
- DOMAIN-SUFFIX,bankmobilevibe.com,Nexuser-ADM
- DOMAIN-SUFFIX,bing.com,Nexuser-ADM
- DOMAIN-SUFFIX,booktopia.com.au,Nexuser-ADM
- DOMAIN-SUFFIX,cccat.io,Nexuser-ADM
- DOMAIN-SUFFIX,centauro.com.br,Nexuser-ADM
- DOMAIN-SUFFIX,clearsurance.com,Nexuser-ADM
- DOMAIN-SUFFIX,costco.com,Nexuser-ADM
- DOMAIN-SUFFIX,crackle.com,Nexuser-ADM
- DOMAIN-SUFFIX,depositphotos.cn,Nexuser-ADM
- DOMAIN-SUFFIX,dish.com,Nexuser-ADM
- DOMAIN-SUFFIX,dmm.co.jp,Nexuser-ADM
- DOMAIN-SUFFIX,dmm.com,Nexuser-ADM
- DOMAIN-SUFFIX,dnvod.tv,Nexuser-ADM
- DOMAIN-SUFFIX,esurance.com,Nexuser-ADM
- DOMAIN-SUFFIX,extmatrix.com,Nexuser-ADM
- DOMAIN-SUFFIX,fastpic.ru,Nexuser-ADM
- DOMAIN-SUFFIX,flipboard.com,Nexuser-ADM
- DOMAIN-SUFFIX,fnac.be,Nexuser-ADM
- DOMAIN-SUFFIX,fnac.com,Nexuser-ADM
- DOMAIN-SUFFIX,funkyimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,fxnetworks.com,Nexuser-ADM
- DOMAIN-SUFFIX,gettyimages.com,Nexuser-ADM
- DOMAIN-SUFFIX,go.com,Nexuser-ADM
- DOMAIN-SUFFIX,here.com,Nexuser-ADM
- DOMAIN-SUFFIX,jcpenney.com,Nexuser-ADM
- DOMAIN-SUFFIX,jiehua.tv,Nexuser-ADM
- DOMAIN-SUFFIX,mailfence.com,Nexuser-ADM
- DOMAIN-SUFFIX,nationwide.com,Nexuser-ADM
- DOMAIN-SUFFIX,nbc.com,Nexuser-ADM
- DOMAIN-SUFFIX,nexon.com,Nexuser-ADM
- DOMAIN-SUFFIX,nordstrom.com,Nexuser-ADM
- DOMAIN-SUFFIX,nordstromimage.com,Nexuser-ADM
- DOMAIN-SUFFIX,nordstromrack.com,Nexuser-ADM
- DOMAIN-SUFFIX,superpages.com,Nexuser-ADM
- DOMAIN-SUFFIX,target.com,Nexuser-ADM
- DOMAIN-SUFFIX,thinkgeek.com,Nexuser-ADM
- DOMAIN-SUFFIX,tracfone.com,Nexuser-ADM
- DOMAIN-SUFFIX,unity3d.com,Nexuser-ADM
- DOMAIN-SUFFIX,uploader.jp,Nexuser-ADM
- DOMAIN-SUFFIX,vevo.com,Nexuser-ADM
- DOMAIN-SUFFIX,viu.tv,Nexuser-ADM
- DOMAIN-SUFFIX,vk.com,Nexuser-ADM
- DOMAIN-SUFFIX,vsco.co,Nexuser-ADM
- DOMAIN-SUFFIX,xfinity.com,Nexuser-ADM
- DOMAIN-SUFFIX,zattoo.com,Nexuser-ADM
# USER-AGENT,Roam*,Nexuser-ADM

# (The Most Popular Sites)
# > Nexuser-ADM
# >> TestFlight
- DOMAIN,testflight.apple.com,Nexuser-ADM
# >> Nexuser-ADM URL Shortener
- DOMAIN-SUFFIX,appsto.re,Nexuser-ADM
# >> iBooks Store download
- DOMAIN,books.itunes.apple.com,Nexuser-ADM
# >> iTunes Store Moveis Trailers
- DOMAIN,hls.itunes.apple.com,Nexuser-ADM
# >> App Store Preview
- DOMAIN,apps.apple.com,Nexuser-ADM
- DOMAIN,itunes.apple.com,Nexuser-ADM
# >> Spotlight
- DOMAIN,api-glb-sea.smoot.apple.com,Nexuser-ADM
# >> Dictionary
- DOMAIN,lookup-api.apple.com,Nexuser-ADM
# > Google
- DOMAIN-SUFFIX,abc.xyz,Nexuser-ADM
- DOMAIN-SUFFIX,android.com,Nexuser-ADM
- DOMAIN-SUFFIX,androidify.com,Nexuser-ADM
- DOMAIN-SUFFIX,dialogflow.com,Nexuser-ADM
- DOMAIN-SUFFIX,autodraw.com,Nexuser-ADM
- DOMAIN-SUFFIX,capitalg.com,Nexuser-ADM
- DOMAIN-SUFFIX,certificate-transparency.org,Nexuser-ADM
- DOMAIN-SUFFIX,chrome.com,Nexuser-ADM
- DOMAIN-SUFFIX,chromeexperiments.com,Nexuser-ADM
- DOMAIN-SUFFIX,chromestatus.com,Nexuser-ADM
- DOMAIN-SUFFIX,chromium.org,Nexuser-ADM
- DOMAIN-SUFFIX,creativelab5.com,Nexuser-ADM
- DOMAIN-SUFFIX,debug.com,Nexuser-ADM
- DOMAIN-SUFFIX,deepmind.com,Nexuser-ADM
- DOMAIN-SUFFIX,firebaseio.com,Nexuser-ADM
- DOMAIN-SUFFIX,getmdl.io,Nexuser-ADM
- DOMAIN-SUFFIX,ggpht.com,Nexuser-ADM
- DOMAIN-SUFFIX,gmail.com,Nexuser-ADM
- DOMAIN-SUFFIX,gmodules.com,Nexuser-ADM
- DOMAIN-SUFFIX,godoc.org,Nexuser-ADM
- DOMAIN-SUFFIX,golang.org,Nexuser-ADM
- DOMAIN-SUFFIX,gstatic.com,Nexuser-ADM
- DOMAIN-SUFFIX,gv.com,Nexuser-ADM
- DOMAIN-SUFFIX,gwtproject.org,Nexuser-ADM
- DOMAIN-SUFFIX,itasoftware.com,Nexuser-ADM
- DOMAIN-SUFFIX,madewithcode.com,Nexuser-ADM
- DOMAIN-SUFFIX,material.io,Nexuser-ADM
- DOMAIN-SUFFIX,polymer-project.org,Nexuser-ADM
- DOMAIN-SUFFIX,admin.recaptcha.net,Nexuser-ADM
- DOMAIN-SUFFIX,recaptcha.net,Nexuser-ADM
- DOMAIN-SUFFIX,shattered.io,Nexuser-ADM
- DOMAIN-SUFFIX,synergyse.com,Nexuser-ADM
- DOMAIN-SUFFIX,tensorflow.org,Nexuser-ADM
- DOMAIN-SUFFIX,tfhub.dev,Nexuser-ADM
- DOMAIN-SUFFIX,tiltbrush.com,Nexuser-ADM
- DOMAIN-SUFFIX,waveprotocol.org,Nexuser-ADM
- DOMAIN-SUFFIX,waymo.com,Nexuser-ADM
- DOMAIN-SUFFIX,webmproject.org,Nexuser-ADM
- DOMAIN-SUFFIX,webrtc.org,Nexuser-ADM
- DOMAIN-SUFFIX,whatbrowser.org,Nexuser-ADM
- DOMAIN-SUFFIX,widevine.com,Nexuser-ADM
- DOMAIN-SUFFIX,x.company,Nexuser-ADM
- DOMAIN-SUFFIX,youtu.be,Nexuser-ADM
- DOMAIN-SUFFIX,yt.be,Nexuser-ADM
- DOMAIN-SUFFIX,ytimg.com,Nexuser-ADM
# > Microsoft
# >> Microsoft OneDrive
- DOMAIN-SUFFIX,1drv.com,Nexuser-ADM
- DOMAIN-SUFFIX,1drv.ms,Nexuser-ADM
- DOMAIN-SUFFIX,blob.core.windows.net,Nexuser-ADM
- DOMAIN-SUFFIX,livefilestore.com,Nexuser-ADM
- DOMAIN-SUFFIX,onedrive.com,Nexuser-ADM
- DOMAIN-SUFFIX,storage.live.com,Nexuser-ADM
- DOMAIN-SUFFIX,storage.msn.com,Nexuser-ADM
- DOMAIN,oneclient.sfx.ms,Nexuser-ADM
# > Other
- DOMAIN-SUFFIX,0rz.tw,Nexuser-ADM
- DOMAIN-SUFFIX,4bluestones.biz,Nexuser-ADM
- DOMAIN-SUFFIX,9bis.net,Nexuser-ADM
- DOMAIN-SUFFIX,allconnected.co,Nexuser-ADM
- DOMAIN-SUFFIX,aol.com,Nexuser-ADM
- DOMAIN-SUFFIX,bcc.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,bit.ly,Nexuser-ADM
- DOMAIN-SUFFIX,bitshare.com,Nexuser-ADM
- DOMAIN-SUFFIX,blog.jp,Nexuser-ADM
- DOMAIN-SUFFIX,blogimg.jp,Nexuser-ADM
- DOMAIN-SUFFIX,blogtd.org,Nexuser-ADM
- DOMAIN-SUFFIX,broadcast.co.nz,Nexuser-ADM
- DOMAIN-SUFFIX,camfrog.com,Nexuser-ADM
- DOMAIN-SUFFIX,cfos.de,Nexuser-ADM
- DOMAIN-SUFFIX,citypopulation.de,Nexuser-ADM
- DOMAIN-SUFFIX,cloudfront.net,Nexuser-ADM
- DOMAIN-SUFFIX,ctitv.com.tw,Nexuser-ADM
- DOMAIN-SUFFIX,cuhk.edu.hk,Nexuser-ADM
- DOMAIN-SUFFIX,cusu.hk,Nexuser-ADM
- DOMAIN-SUFFIX,discord.gg,Nexuser-ADM
- DOMAIN-SUFFIX,discuss.com.hk,Nexuser-ADM
- DOMAIN-SUFFIX,dropboxapi.com,Nexuser-ADM
- DOMAIN-SUFFIX,duolingo.cn,Nexuser-ADM
- DOMAIN-SUFFIX,edditstatic.com,Nexuser-ADM
- DOMAIN-SUFFIX,flickriver.com,Nexuser-ADM
- DOMAIN-SUFFIX,focustaiwan.tw,Nexuser-ADM
- DOMAIN-SUFFIX,free.fr,Nexuser-ADM
- DOMAIN-SUFFIX,gigacircle.com,Nexuser-ADM
- DOMAIN-SUFFIX,hk-pub.com,Nexuser-ADM
- DOMAIN-SUFFIX,hosting.co.uk,Nexuser-ADM
- DOMAIN-SUFFIX,hwcdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,ifixit.com,Nexuser-ADM
- DOMAIN-SUFFIX,iphone4hongkong.com,Nexuser-ADM
- DOMAIN-SUFFIX,iphonetaiwan.org,Nexuser-ADM
- DOMAIN-SUFFIX,iptvbin.com,Nexuser-ADM
- DOMAIN-SUFFIX,linksalpha.com,Nexuser-ADM
- DOMAIN-SUFFIX,manyvids.com,Nexuser-ADM
- DOMAIN-SUFFIX,myactimes.com,Nexuser-ADM
- DOMAIN-SUFFIX,newsblur.com,Nexuser-ADM
- DOMAIN-SUFFIX,now.im,Nexuser-ADM
- DOMAIN-SUFFIX,nowe.com,Nexuser-ADM
- DOMAIN-SUFFIX,redditlist.com,Nexuser-ADM
- DOMAIN-SUFFIX,s3.amazonaws.com,Nexuser-ADM
- DOMAIN-SUFFIX,signal.org,Nexuser-ADM
- DOMAIN-SUFFIX,smartmailcloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,sparknotes.com,Nexuser-ADM
- DOMAIN-SUFFIX,streetvoice.com,Nexuser-ADM
- DOMAIN-SUFFIX,supertop.co,Nexuser-ADM
- DOMAIN-SUFFIX,tv.com,Nexuser-ADM
- DOMAIN-SUFFIX,typepad.com,Nexuser-ADM
- DOMAIN-SUFFIX,udnbkk.com,Nexuser-ADM
- DOMAIN-SUFFIX,urbanairship.com,Nexuser-ADM
- DOMAIN-SUFFIX,whispersystems.org,Nexuser-ADM
- DOMAIN-SUFFIX,wikia.com,Nexuser-ADM
- DOMAIN-SUFFIX,wn.com,Nexuser-ADM
- DOMAIN-SUFFIX,wolframalpha.com,Nexuser-ADM
- DOMAIN-SUFFIX,x-art.com,Nexuser-ADM
- DOMAIN-SUFFIX,yimg.com,Nexuser-ADM
- DOMAIN,api.steampowered.com,Nexuser-ADM
- DOMAIN,store.steampowered.com,Nexuser-ADM

# China Area Network
# > 360
- DOMAIN-SUFFIX,qhres.com,Nexuser-ADM
- DOMAIN-SUFFIX,qhimg.com,Nexuser-ADM
# > Akamai
- DOMAIN-SUFFIX,akadns.net,Nexuser-ADM
# - DOMAIN-SUFFIX,akamai.net,Nexuser-ADM
# - DOMAIN-SUFFIX,akamaiedge.net,Nexuser-ADM
# - DOMAIN-SUFFIX,akamaihd.net,Nexuser-ADM
# - DOMAIN-SUFFIX,akamaistream.net,Nexuser-ADM
# - DOMAIN-SUFFIX,akamaized.net,Nexuser-ADM
# > Alibaba
# USER-AGENT,%E4%BC%98%E9%85%B7*,Nexuser-ADM
- DOMAIN-SUFFIX,alibaba.com,Nexuser-ADM
- DOMAIN-SUFFIX,alicdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,alikunlun.com,Nexuser-ADM
- DOMAIN-SUFFIX,alipay.com,Nexuser-ADM
- DOMAIN-SUFFIX,amap.com,Nexuser-ADM
- DOMAIN-SUFFIX,autonavi.com,Nexuser-ADM
- DOMAIN-SUFFIX,dingtalk.com,Nexuser-ADM
- DOMAIN-SUFFIX,mxhichina.com,Nexuser-ADM
- DOMAIN-SUFFIX,soku.com,Nexuser-ADM
- DOMAIN-SUFFIX,taobao.com,Nexuser-ADM
- DOMAIN-SUFFIX,tmall.com,Nexuser-ADM
- DOMAIN-SUFFIX,tmall.hk,Nexuser-ADM
- DOMAIN-SUFFIX,ykimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,youku.com,Nexuser-ADM
- DOMAIN-SUFFIX,xiami.com,Nexuser-ADM
- DOMAIN-SUFFIX,xiami.net,Nexuser-ADM
# > Baidu
- DOMAIN-SUFFIX,baidu.com,Nexuser-ADM
- DOMAIN-SUFFIX,baidubcr.com,Nexuser-ADM
- DOMAIN-SUFFIX,bdstatic.com,Nexuser-ADM
- DOMAIN-SUFFIX,yunjiasu-cdn.net,Nexuser-ADM
# > bilibili
- DOMAIN-SUFFIX,acgvideo.com,Nexuser-ADM
- DOMAIN-SUFFIX,biliapi.com,Nexuser-ADM
- DOMAIN-SUFFIX,biliapi.net,Nexuser-ADM
- DOMAIN-SUFFIX,bilibili.com,Nexuser-ADM
- DOMAIN-SUFFIX,bilibili.tv,Nexuser-ADM
- DOMAIN-SUFFIX,hdslb.com,Nexuser-ADM
# > Blizzard
- DOMAIN-SUFFIX,blizzard.com,Nexuser-ADM
- DOMAIN-SUFFIX,battle.net,Nexuser-ADM
- DOMAIN,blzddist1-a.akamaihd.net,Nexuser-ADM
# > ByteDance
- DOMAIN-SUFFIX,feiliao.com,Nexuser-ADM
- DOMAIN-SUFFIX,pstatp.com,Nexuser-ADM
- DOMAIN-SUFFIX,snssdk.com,Nexuser-ADM
- DOMAIN-SUFFIX,iesdouyin.com,Nexuser-ADM
- DOMAIN-SUFFIX,toutiao.com,Nexuser-ADM
# > CCTV
- DOMAIN-SUFFIX,cctv.com,Nexuser-ADM
- DOMAIN-SUFFIX,cctvpic.com,Nexuser-ADM
- DOMAIN-SUFFIX,livechina.com,Nexuser-ADM
# > DiDi
- DOMAIN-SUFFIX,didialift.com,Nexuser-ADM
- DOMAIN-SUFFIX,didiglobal.com,Nexuser-ADM
- DOMAIN-SUFFIX,udache.com,Nexuser-ADM
# > 蛋蛋赞
- DOMAIN-SUFFIX,343480.com,Nexuser-ADM
- DOMAIN-SUFFIX,baduziyuan.com,Nexuser-ADM
- DOMAIN-SUFFIX,com-hs-hkdy.com,Nexuser-ADM
- DOMAIN-SUFFIX,czybjz.com,Nexuser-ADM
- DOMAIN-SUFFIX,dandanzan.com,Nexuser-ADM
- DOMAIN-SUFFIX,fjhps.com,Nexuser-ADM
- DOMAIN-SUFFIX,kuyunbo.club,Nexuser-ADM
# > ChinaNet
- DOMAIN-SUFFIX,21cn.com,Nexuser-ADM
# > HunanTV
- DOMAIN-SUFFIX,hitv.com,Nexuser-ADM
- DOMAIN-SUFFIX,mgtv.com,Nexuser-ADM
# > iQiyi
- DOMAIN-SUFFIX,iqiyi.com,Nexuser-ADM
- DOMAIN-SUFFIX,iqiyipic.com,Nexuser-ADM
- DOMAIN-SUFFIX,71.am.com,Nexuser-ADM
# > JD
- DOMAIN-SUFFIX,jd.com,Nexuser-ADM
- DOMAIN-SUFFIX,jd.hk,Nexuser-ADM
- DOMAIN-SUFFIX,jdpay.com,Nexuser-ADM
- DOMAIN-SUFFIX,360buyimg.com,Nexuser-ADM
# > Kingsoft
- DOMAIN-SUFFIX,iciba.com,Nexuser-ADM
- DOMAIN-SUFFIX,ksosoft.com,Nexuser-ADM
# > Meitu
- DOMAIN-SUFFIX,meitu.com,Nexuser-ADM
- DOMAIN-SUFFIX,meitudata.com,Nexuser-ADM
- DOMAIN-SUFFIX,meitustat.com,Nexuser-ADM
- DOMAIN-SUFFIX,meipai.com,Nexuser-ADM
# > MI
- DOMAIN-SUFFIX,duokan.com,Nexuser-ADM
- DOMAIN-SUFFIX,mi-img.com,Nexuser-ADM
- DOMAIN-SUFFIX,miui.com,Nexuser-ADM
- DOMAIN-SUFFIX,miwifi.com,Nexuser-ADM
- DOMAIN-SUFFIX,xiaomi.com,Nexuser-ADM
# > Microsoft
- DOMAIN-SUFFIX,microsoft.com,Nexuser-ADM
- DOMAIN-SUFFIX,msecnd.net,Nexuser-ADM
- DOMAIN-SUFFIX,office365.com,Nexuser-ADM
- DOMAIN-SUFFIX,outlook.com,Nexuser-ADM
- DOMAIN-SUFFIX,s-microsoft.com,Nexuser-ADM
- DOMAIN-SUFFIX,visualstudio.com,Nexuser-ADM
- DOMAIN-SUFFIX,windows.com,Nexuser-ADM
- DOMAIN-SUFFIX,windowsupdate.com,Nexuser-ADM
- DOMAIN,officecdn-microsoft-com.akamaized.net,Nexuser-ADM
# > NetEase
# USER-AGENT,NeteaseMusic*,Nexuser-ADM
# USER-AGENT,%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90*,Nexuser-ADM
- DOMAIN-SUFFIX,163.com,Nexuser-ADM
- DOMAIN-SUFFIX,126.net,Nexuser-ADM
- DOMAIN-SUFFIX,127.net,Nexuser-ADM
- DOMAIN-SUFFIX,163yun.com,Nexuser-ADM
- DOMAIN-SUFFIX,lofter.com,Nexuser-ADM
- DOMAIN-SUFFIX,netease.com,Nexuser-ADM
- DOMAIN-SUFFIX,ydstatic.com,Nexuser-ADM
# > Sina
- DOMAIN-SUFFIX,sina.com,Nexuser-ADM
- DOMAIN-SUFFIX,weibo.com,Nexuser-ADM
- DOMAIN-SUFFIX,weibocdn.com,Nexuser-ADM
# > Sohu
- DOMAIN-SUFFIX,sohu.com,Nexuser-ADM
- DOMAIN-SUFFIX,sohucs.com,Nexuser-ADM
- DOMAIN-SUFFIX,sohu-inc.com,Nexuser-ADM
- DOMAIN-SUFFIX,v-56.com,Nexuser-ADM
# > Sogo
- DOMAIN-SUFFIX,sogo.com,Nexuser-ADM
- DOMAIN-SUFFIX,sogou.com,Nexuser-ADM
- DOMAIN-SUFFIX,sogoucdn.com,Nexuser-ADM
# > Steam
- DOMAIN-SUFFIX,steampowered.com,Nexuser-ADM
- DOMAIN-SUFFIX,steam-chat.com,Nexuser-ADM
- DOMAIN-SUFFIX,steamgames.com,Nexuser-ADM
- DOMAIN-SUFFIX,steamusercontent.com,Nexuser-ADM
- DOMAIN-SUFFIX,steamcontent.com,Nexuser-ADM
- DOMAIN-SUFFIX,steamstatic.com,Nexuser-ADM
- DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,Nexuser-ADM
- DOMAIN-SUFFIX,steamstat.us,Nexuser-ADM
# > Tencent
# USER-AGENT,MicroMessenger%20Client,Nexuser-ADM
# USER-AGENT,WeChat*,Nexuser-ADM
- DOMAIN-SUFFIX,gtimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,idqqimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,igamecj.com,Nexuser-ADM
- DOMAIN-SUFFIX,myapp.com,Nexuser-ADM
- DOMAIN-SUFFIX,myqcloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,qq.com,Nexuser-ADM
- DOMAIN-SUFFIX,tencent.com,Nexuser-ADM
- DOMAIN-SUFFIX,tencent-cloud.net,Nexuser-ADM
# > YYeTs
# USER-AGENT,YYeTs*,Nexuser-ADM
- DOMAIN-SUFFIX,jstucdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,zimuzu.io,Nexuser-ADM
- DOMAIN-SUFFIX,zimuzu.tv,Nexuser-ADM
- DOMAIN-SUFFIX,zmz2019.com,Nexuser-ADM
- DOMAIN-SUFFIX,zmzapi.com,Nexuser-ADM
- DOMAIN-SUFFIX,zmzapi.net,Nexuser-ADM
- DOMAIN-SUFFIX,zmzfile.com,Nexuser-ADM
# > Content Delivery Network
- DOMAIN-SUFFIX,ccgslb.com,Nexuser-ADM
- DOMAIN-SUFFIX,ccgslb.net,Nexuser-ADM
- DOMAIN-SUFFIX,chinanetcenter.com,Nexuser-ADM
- DOMAIN-SUFFIX,meixincdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,ourdvs.com,Nexuser-ADM
- DOMAIN-SUFFIX,staticdn.net,Nexuser-ADM
- DOMAIN-SUFFIX,wangsu.com,Nexuser-ADM
# > IP Query
- DOMAIN-SUFFIX,ipip.net,Nexuser-ADM
- DOMAIN-SUFFIX,ip.la,Nexuser-ADM
- DOMAIN-SUFFIX,ip-cdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,ipv6-test.com,Nexuser-ADM
- DOMAIN-SUFFIX,test-ipv6.com,Nexuser-ADM
- DOMAIN-SUFFIX,whatismyip.com,Nexuser-ADM
# > Speed Test
# - DOMAIN-SUFFIX,speedtest.net,Nexuser-ADM
- DOMAIN-SUFFIX,netspeedtestmaster.com,Nexuser-ADM
- DOMAIN,speedtest.macpaw.com,Nexuser-ADM
# > Private Tracker
- DOMAIN-SUFFIX,awesome-hd.me,Nexuser-ADM
- DOMAIN-SUFFIX,broadcasthe.net,Nexuser-ADM
- DOMAIN-SUFFIX,chdbits.co,Nexuser-ADM
- DOMAIN-SUFFIX,classix-unlimited.co.uk,Nexuser-ADM
- DOMAIN-SUFFIX,empornium.me,Nexuser-ADM
- DOMAIN-SUFFIX,gazellegames.net,Nexuser-ADM
- DOMAIN-SUFFIX,hdchina.org,Nexuser-ADM
- DOMAIN-SUFFIX,hdsky.me,Nexuser-ADM
- DOMAIN-SUFFIX,icetorrent.org,Nexuser-ADM
- DOMAIN-SUFFIX,jpopsuki.eu,Nexuser-ADM
- DOMAIN-SUFFIX,keepfrds.com,Nexuser-ADM
- DOMAIN-SUFFIX,madsrevolution.net,Nexuser-ADM
- DOMAIN-SUFFIX,m-team.cc,Nexuser-ADM
- DOMAIN-SUFFIX,nanyangpt.com,Nexuser-ADM
- DOMAIN-SUFFIX,ncore.cc,Nexuser-ADM
- DOMAIN-SUFFIX,open.cd,Nexuser-ADM
- DOMAIN-SUFFIX,ourbits.club,Nexuser-ADM
- DOMAIN-SUFFIX,passthepopcorn.me,Nexuser-ADM
- DOMAIN-SUFFIX,privatehd.to,Nexuser-ADM
- DOMAIN-SUFFIX,redacted.ch,Nexuser-ADM
- DOMAIN-SUFFIX,springsunday.net,Nexuser-ADM
- DOMAIN-SUFFIX,tjupt.org,Nexuser-ADM
- DOMAIN-SUFFIX,totheglory.im,Nexuser-ADM
# > Scholar
- DOMAIN-SUFFIX,acm.org,Nexuser-ADM
- DOMAIN-SUFFIX,acs.org,Nexuser-ADM
- DOMAIN-SUFFIX,aip.org,Nexuser-ADM
- DOMAIN-SUFFIX,ams.org,Nexuser-ADM
- DOMAIN-SUFFIX,annualreviews.org,Nexuser-ADM
- DOMAIN-SUFFIX,aps.org,Nexuser-ADM
- DOMAIN-SUFFIX,ascelibrary.org,Nexuser-ADM
- DOMAIN-SUFFIX,asm.org,Nexuser-ADM
- DOMAIN-SUFFIX,asme.org,Nexuser-ADM
- DOMAIN-SUFFIX,astm.org,Nexuser-ADM
- DOMAIN-SUFFIX,bmj.com,Nexuser-ADM
- DOMAIN-SUFFIX,cambridge.org,Nexuser-ADM
- DOMAIN-SUFFIX,cas.org,Nexuser-ADM
- DOMAIN-SUFFIX,clarivate.com,Nexuser-ADM
- DOMAIN-SUFFIX,ebscohost.com,Nexuser-ADM
- DOMAIN-SUFFIX,emerald.com,Nexuser-ADM
- DOMAIN-SUFFIX,engineeringvillage.com,Nexuser-ADM
- DOMAIN-SUFFIX,icevirtuallibrary.com,Nexuser-ADM
- DOMAIN-SUFFIX,ieee.org,Nexuser-ADM
- DOMAIN-SUFFIX,imf.org,Nexuser-ADM
- DOMAIN-SUFFIX,iop.org,Nexuser-ADM
- DOMAIN-SUFFIX,jamanetwork.com,Nexuser-ADM
- DOMAIN-SUFFIX,jhu.edu,Nexuser-ADM
- DOMAIN-SUFFIX,jstor.org,Nexuser-ADM
- DOMAIN-SUFFIX,karger.com,Nexuser-ADM
- DOMAIN-SUFFIX,libguides.com,Nexuser-ADM
- DOMAIN-SUFFIX,madsrevolution.net,Nexuser-ADM
- DOMAIN-SUFFIX,mpg.de,Nexuser-ADM
- DOMAIN-SUFFIX,myilibrary.com,Nexuser-ADM
- DOMAIN-SUFFIX,nature.com,Nexuser-ADM
- DOMAIN-SUFFIX,oecd-ilibrary.org,Nexuser-ADM
- DOMAIN-SUFFIX,osapublishing.org,Nexuser-ADM
- DOMAIN-SUFFIX,oup.com,Nexuser-ADM
- DOMAIN-SUFFIX,ovid.com,Nexuser-ADM
- DOMAIN-SUFFIX,oxfordartonline.com,Nexuser-ADM
- DOMAIN-SUFFIX,oxfordbibliographies.com,Nexuser-ADM
- DOMAIN-SUFFIX,oxfordmusiconline.com,Nexuser-ADM
- DOMAIN-SUFFIX,pnas.org,Nexuser-ADM
- DOMAIN-SUFFIX,proquest.com,Nexuser-ADM
- DOMAIN-SUFFIX,rsc.org,Nexuser-ADM
- DOMAIN-SUFFIX,sagepub.com,Nexuser-ADM
- DOMAIN-SUFFIX,sciencedirect.com,Nexuser-ADM
- DOMAIN-SUFFIX,sciencemag.org,Nexuser-ADM
- DOMAIN-SUFFIX,scopus.com,Nexuser-ADM
- DOMAIN-SUFFIX,siam.org,Nexuser-ADM
- DOMAIN-SUFFIX,spiedigitallibrary.org,Nexuser-ADM
- DOMAIN-SUFFIX,springer.com,Nexuser-ADM
- DOMAIN-SUFFIX,springerlink.com,Nexuser-ADM
- DOMAIN-SUFFIX,tandfonline.com,Nexuser-ADM
- DOMAIN-SUFFIX,un.org,Nexuser-ADM
- DOMAIN-SUFFIX,uni-bielefeld.de,Nexuser-ADM
- DOMAIN-SUFFIX,webofknowledge.com,Nexuser-ADM
- DOMAIN-SUFFIX,westlaw.com,Nexuser-ADM
- DOMAIN-SUFFIX,wiley.com,Nexuser-ADM
- DOMAIN-SUFFIX,worldbank.org,Nexuser-ADM
- DOMAIN-SUFFIX,worldscientific.com,Nexuser-ADM
# > Plex Media Server
- DOMAIN-SUFFIX,plex.tv,Nexuser-ADM
# > Other
- DOMAIN-SUFFIX,cn,Nexuser-ADM
- DOMAIN-SUFFIX,360in.com,Nexuser-ADM
- DOMAIN-SUFFIX,51ym.me,Nexuser-ADM
- DOMAIN-SUFFIX,8686c.com,Nexuser-ADM
- DOMAIN-SUFFIX,abchina.com,Nexuser-ADM
- DOMAIN-SUFFIX,accuweather.com,Nexuser-ADM
- DOMAIN-SUFFIX,aicoinstorge.com,Nexuser-ADM
- DOMAIN-SUFFIX,air-matters.com,Nexuser-ADM
- DOMAIN-SUFFIX,air-matters.io,Nexuser-ADM
- DOMAIN-SUFFIX,aixifan.com,Nexuser-ADM
- DOMAIN-SUFFIX,amd.com,Nexuser-ADM
- DOMAIN-SUFFIX,b612.net,Nexuser-ADM
- DOMAIN-SUFFIX,bdatu.com,Nexuser-ADM
- DOMAIN-SUFFIX,beitaichufang.com,Nexuser-ADM
- DOMAIN-SUFFIX,bjango.com,Nexuser-ADM
- DOMAIN-SUFFIX,booking.com,Nexuser-ADM
- DOMAIN-SUFFIX,bstatic.com,Nexuser-ADM
- DOMAIN-SUFFIX,cailianpress.com,Nexuser-ADM
- DOMAIN-SUFFIX,camera360.com,Nexuser-ADM
- DOMAIN-SUFFIX,chinaso.com,Nexuser-ADM
- DOMAIN-SUFFIX,chua.pro,Nexuser-ADM
- DOMAIN-SUFFIX,chuimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,chunyu.mobi,Nexuser-ADM
- DOMAIN-SUFFIX,chushou.tv,Nexuser-ADM
- DOMAIN-SUFFIX,cmbchina.com,Nexuser-ADM
- DOMAIN-SUFFIX,cmbimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,ctrip.com,Nexuser-ADM
- DOMAIN-SUFFIX,dfcfw.com,Nexuser-ADM
- DOMAIN-SUFFIX,docschina.org,Nexuser-ADM
- DOMAIN-SUFFIX,douban.com,Nexuser-ADM
- DOMAIN-SUFFIX,doubanio.com,Nexuser-ADM
- DOMAIN-SUFFIX,douyu.com,Nexuser-ADM
- DOMAIN-SUFFIX,dxycdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,dytt8.net,Nexuser-ADM
- DOMAIN-SUFFIX,eastmoney.com,Nexuser-ADM
- DOMAIN-SUFFIX,eudic.net,Nexuser-ADM
- DOMAIN-SUFFIX,feng.com,Nexuser-ADM
- DOMAIN-SUFFIX,fengkongcloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,frdic.com,Nexuser-ADM
- DOMAIN-SUFFIX,futu5.com,Nexuser-ADM
- DOMAIN-SUFFIX,futunn.com,Nexuser-ADM
- DOMAIN-SUFFIX,gandi.net,Nexuser-ADM
- DOMAIN-SUFFIX,geilicdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,getpricetag.com,Nexuser-ADM
- DOMAIN-SUFFIX,gifshow.com,Nexuser-ADM
- DOMAIN-SUFFIX,godic.net,Nexuser-ADM
- DOMAIN-SUFFIX,hicloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,hongxiu.com,Nexuser-ADM
- DOMAIN-SUFFIX,hostbuf.com,Nexuser-ADM
- DOMAIN-SUFFIX,huxiucdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,huya.com,Nexuser-ADM
- DOMAIN-SUFFIX,infinitynewtab.com,Nexuser-ADM
- DOMAIN-SUFFIX,ithome.com,Nexuser-ADM
- DOMAIN-SUFFIX,java.com,Nexuser-ADM
- DOMAIN-SUFFIX,jidian.im,Nexuser-ADM
- DOMAIN-SUFFIX,kaiyanapp.com,Nexuser-ADM
- DOMAIN-SUFFIX,kaspersky-labs.com,Nexuser-ADM
- DOMAIN-SUFFIX,keepcdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,kkmh.com,Nexuser-ADM
- DOMAIN-SUFFIX,licdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,linkedin.com,Nexuser-ADM
- DOMAIN-SUFFIX,loli.net,Nexuser-ADM
- DOMAIN-SUFFIX,luojilab.com,Nexuser-ADM
- DOMAIN-SUFFIX,maoyan.com,Nexuser-ADM
- DOMAIN-SUFFIX,maoyun.tv,Nexuser-ADM
- DOMAIN-SUFFIX,meituan.com,Nexuser-ADM
- DOMAIN-SUFFIX,meituan.net,Nexuser-ADM
- DOMAIN-SUFFIX,mobike.com,Nexuser-ADM
- DOMAIN-SUFFIX,moke.com,Nexuser-ADM
- DOMAIN-SUFFIX,mubu.com,Nexuser-ADM
- DOMAIN-SUFFIX,myzaker.com,Nexuser-ADM
- DOMAIN-SUFFIX,nim-lang-cn.org,Nexuser-ADM
- DOMAIN-SUFFIX,nvidia.com,Nexuser-ADM
- DOMAIN-SUFFIX,oracle.com,Nexuser-ADM
- DOMAIN-SUFFIX,paypal.com,Nexuser-ADM
- DOMAIN-SUFFIX,paypalobjects.com,Nexuser-ADM
- DOMAIN-SUFFIX,qdaily.com,Nexuser-ADM
- DOMAIN-SUFFIX,qidian.com,Nexuser-ADM
- DOMAIN-SUFFIX,qyer.com,Nexuser-ADM
- DOMAIN-SUFFIX,qyerstatic.com,Nexuser-ADM
- DOMAIN-SUFFIX,raychase.net,Nexuser-ADM
- DOMAIN-SUFFIX,ronghub.com,Nexuser-ADM
- DOMAIN-SUFFIX,ruguoapp.com,Nexuser-ADM
- DOMAIN-SUFFIX,s-reader.com,Nexuser-ADM
- DOMAIN-SUFFIX,sankuai.com,Nexuser-ADM
- DOMAIN-SUFFIX,scomper.me,Nexuser-ADM
- DOMAIN-SUFFIX,seafile.com,Nexuser-ADM
- DOMAIN-SUFFIX,sm.ms,Nexuser-ADM
- DOMAIN-SUFFIX,smzdm.com,Nexuser-ADM
- DOMAIN-SUFFIX,snapdrop.net,Nexuser-ADM
- DOMAIN-SUFFIX,snwx.com,Nexuser-ADM
- DOMAIN-SUFFIX,sspai.com,Nexuser-ADM
- DOMAIN-SUFFIX,takungpao.com,Nexuser-ADM
- DOMAIN-SUFFIX,teamviewer.com,Nexuser-ADM
- DOMAIN-SUFFIX,tianyancha.com,Nexuser-ADM
- DOMAIN-SUFFIX,udacity.com,Nexuser-ADM
- DOMAIN-SUFFIX,uning.com,Nexuser-ADM
- DOMAIN-SUFFIX,vmware.com,Nexuser-ADM
- DOMAIN-SUFFIX,weather.com,Nexuser-ADM
- DOMAIN-SUFFIX,weico.cc,Nexuser-ADM
- DOMAIN-SUFFIX,weidian.com,Nexuser-ADM
- DOMAIN-SUFFIX,xiachufang.com,Nexuser-ADM
- DOMAIN-SUFFIX,ximalaya.com,Nexuser-ADM
- DOMAIN-SUFFIX,xinhuanet.com,Nexuser-ADM
- DOMAIN-SUFFIX,xmcdn.com,Nexuser-ADM
- DOMAIN-SUFFIX,yangkeduo.com,Nexuser-ADM
- DOMAIN-SUFFIX,zhangzishi.cc,Nexuser-ADM
- DOMAIN-SUFFIX,zhihu.com,Nexuser-ADM
- DOMAIN-SUFFIX,zhimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,zhuihd.com,Nexuser-ADM
- DOMAIN,download.jetbrains.com,Nexuser-ADM
- DOMAIN,images-cn.ssl-images-amazon.com,Nexuser-ADM

# > Nexuser-ADM
- DOMAIN-SUFFIX,aaplimg.com,Nexuser-ADM
- DOMAIN-SUFFIX,apple.co,Nexuser-ADM
- DOMAIN-SUFFIX,apple.com,Nexuser-ADM
- DOMAIN-SUFFIX,apple-cloudkit.com,Nexuser-ADM
- DOMAIN-SUFFIX,appstore.com,Nexuser-ADM
- DOMAIN-SUFFIX,cdn-apple.com,Nexuser-ADM
- DOMAIN-SUFFIX,crashlytics.com,Nexuser-ADM
- DOMAIN-SUFFIX,icloud.com,Nexuser-ADM
- DOMAIN-SUFFIX,icloud-content.com,Nexuser-ADM
- DOMAIN-SUFFIX,me.com,Nexuser-ADM
- DOMAIN-SUFFIX,mzstatic.com,Nexuser-ADM
- DOMAIN,www-cdn.icloud.com.akadns.net,Nexuser-ADM
- DOMAIN,clash.razord.top,Nexuser-ADM
- DOMAIN,v2ex.com,Nexuser-ADM
- IP-CIDR,17.0.0.0/8,Nexuser-ADM,no-resolve

# Local Area Network
- IP-CIDR,192.168.0.0/16,Nexuser-ADM
- IP-CIDR,10.0.0.0/8,Nexuser-ADM
- IP-CIDR,172.16.0.0/12,Nexuser-ADM
- IP-CIDR,127.0.0.0/8,Nexuser-ADM
- IP-CIDR,100.64.0.0/10,Nexuser-ADM

# DNSPod Public DNS+
- IP-CIDR,119.28.28.28/32,Nexuser-ADM,no-resolve
# GeoIP China
- GEOIP,CN,Nexuser-ADM

- MATCH,Nexuser-ADM

proxies:' >> /root/.config/clash/config.yaml 
[[ $mode = 2 ]] && echo -e '
proxies:' >> /root/.config/clash/config.yaml 
}

conFIN() {
confRULE
[[ ! -z ${proTRO} ]] && echo -e "${proTRO}" >> /root/.config/clash/config.yaml
[[ ! -z ${proV2R} ]] && echo -e "${proV2R}" >> /root/.config/clash/config.yaml

#echo ''

echo "#POWER BY @Nexuser" >> /root/.config/clash/config.yaml
}

enon(){
		clear
		msg -bar3
		blanco " Se ha agregado un autoejecutor en el Sector de Inicios Rapidos"
		msg -bar3
		blanco "	  Para Acceder al menu Rapido \n	     Utilize * clash.sh * !!!"
		msg -bar3
		echo -e "		\033[4;31mNOTA importante\033[0m"
		echo -e " \033[0;31mSi deseas desabilitar esta opcion, apagala"
		echo -e " Y te recomiendo, no alterar nada en este menu, para"
		echo -e "             Evitar Errores Futuros"
		echo -e " y causar problemas en futuras instalaciones.\033[0m"
		msg -bar3
		continuar
		read foo
}
enoff(){
rm -f /bin/clash.sh
		msg -bar3
		echo -e "		\033[4;31mNOTA importante\033[0m"
		echo -e " \033[0;31mSe ha Desabilitado el menu Rapido de clash.sh"
		echo -e " Y te recomiendo, no alterar nada en este menu, para"
		echo -e "             Evitar Errores Futuros"
		echo -e " y causar problemas en futuras instalaciones.\033[0m"
		msg -bar3
		continuar
		read foo
}

enttrada () {
echo 'source <(curl -sSL https://raw.githubusercontent.com/Nexuser/ScriptCGH/main/HTools/CLASH/ClashForAndroidGLOBAL.sh)' > /bin/clash.sh && chmod +x /bin/clash.sh
}

blanco(){
	[[ !  $2 = 0 ]] && {
		echo -e "\033[1;37m$1\033[0m"
	} || {
		echo -ne " \033[1;37m$1:\033[0m "
	}
}
title(){
	msg -bar3
	blanco "$1"
	msg -bar3
}
col(){
	nom=$(printf '%-55s' "\033[0;92m${1} \033[0;31m>> \033[1;37m${2}")
	echo -e "	$nom\033[0;31m${3}   \033[0;92m${4}\033[0m"
}
col2(){
	echo -e " \033[1;91m$1\033[0m \033[1;37m$2\033[0m"
}
vacio(){
blanco "\n no se puede ingresar campos vacios..."
}
cancelar(){
echo -e "\n \033[3;49;31minstalacion cancelada...\033[0m"
}
continuar(){
echo -e " \033[3;49;32mEnter para continuar...\033[0m"
}
userDat(){
	blanco "	NÂ°    Usuarios 		  fech exp   dias"
	msg -bar3
}
view_usert(){
configt="/usr/local/etc/trojan/config.json"
tempt="/etc/trojan/temp.json"
trojdirt="/etc/trojan" 
user_conft="/etc/trojan/user"
backdirt="/etc/trojan/back" 
tmpdirt="$backdir/tmp"
trojanport=`lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN" | grep trojan | awk '{print substr($9,3); }' > /tmp/trojan.txt && echo | cat /tmp/trojan.txt | tr '\n' ' ' > /bin/ejecutar/trojanports.txt && cat /bin/ejecutar/trojanports.txt`;
troport=$(cat /bin/ejecutar/trojanports.txt  | sed 's/\s\+/,/g' | cut -d , -f1)
	unset seg
	seg=$(date +%s)
	while :
	do
	nick="$(cat $configt | grep ',"')"
	users="$(echo $nick|sed -e 's/[^a-z0-9 -]//ig')"
		title "	ESCOJE USUARIO TROJAN"
		userDat

		n=1
		for i in $users
		do
			unset DateExp
			unset seg_exp
			unset exp

			[[ $i = "Nexuserscript" ]] && {
				i="Admin"
				DateExp=" Ilimitado"
			} || {
				DateExp="$(cat ${user_conft}|grep -w "${i}"|cut -d'|' -f3)"
				seg_exp=$(date +%s --date="$DateExp")
				exp="[$(($(($seg_exp - $seg)) / 86400))]"
			}

			col "$n)" "$i" "$DateExp" "$exp"
			let n++
		done
		msg -bar3
		col "0)" "VOLVER"
		msg -bar3
		blanco "SELECCIONA USUARIO" 0
		read opcion
		[[ -z $opcion ]] && vacio && sleep 0.3s && continue
		[[ $opcion = 0 ]] && tropass="user_null" && break
		n=1
		unset i
		for i in $users
		do
		[[ $n = $opcion ]] && tropass=$i
			let n++
		done
		let opcion--
		addip=$(wget -qO- ifconfig.me)
		echo "USER SELECIONADO : $tropass " 
		break
	done
}

view_user(){
config="/etc/v2ray/config.json"
temp="/etc/v2ray/temp.json"
v2rdir="/etc/v2r" && [[ ! -d $v2rdir ]] && mkdir $v2rdir
user_conf="/etc/v2r/user" && [[ ! -e $user_conf ]] && touch $user_conf
backdir="/etc/v2r/back" && [[ ! -d ${backdir} ]] && mkdir ${backdir}
tmpdir="$backdir/tmp"
	unset seg
	seg=$(date +%s)
	while :
	do
		users=$(cat $config | jq .inbounds[].settings.clients[] | jq -r .email)

		title "	VER USUARIO V2RAY REGISTRADO"
		userDat

		n=1
		for i in $users
		do
			unset DateExp
			unset seg_exp
			unset exp

			[[ $i = null ]] && {
				i="Admin"
				DateExp=" Ilimitado"
			} || {
				DateExp="$(cat ${user_conf}|grep -w "${i}"|cut -d'|' -f3)"
				seg_exp=$(date +%s --date="$DateExp")
				exp="[$(($(($seg_exp - $seg)) / 86400))]"
			}

			col "$n)" "$i" "$DateExp" "$exp"
			let n++
		done

		msg -bar3
		col "0)" "VOLVER"
		msg -bar3
		blanco "Escoje Tu Usuario : " 0
		read opcion
		[[ -z $opcion ]] && vacio && sleep 0.3s && continue
		[[ $opcion = 0 ]] && break
		let opcion--
		ps=$(jq .inbounds[].settings.clients[$opcion].email $config) && [[ $ps = null ]] && ps="default"
		uid=$(jq .inbounds[].settings.clients[$opcion].id $config)
		aluuiid=$(jq .inbounds[].settings.clients[$opcion].alterId $config)
		add=$(jq '.inbounds[].domain' $config) && [[ $add = null ]] && add=$(wget -qO- ipv4.icanhazip.com)
		host=$(jq '.inbounds[].streamSettings.wsSettings.headers.Host' $config) && [[ $host = null ]] && host=''
		net=$(jq '.inbounds[].streamSettings.network' $config)
		parche=$(jq -r .inbounds[].streamSettings.wsSettings.path $config) && [[ $path = null ]] && parche='' 
		v2port=$(jq '.inbounds[].port' $config)
		tls=$(jq '.inbounds[].streamSettings.security' $config)
		[[ $net = '"grpc"' ]] && path=$(jq '.inbounds[].streamSettings.grpcSettings.serviceName'  $config) || path=$(jq '.inbounds[].streamSettings.wsSettings.path' $config)
		addip=$(wget -qO- ifconfig.me)
		echo "Usuario $ps Seleccionado" 
		break
	done
}

[[ ! -d /root/.config/clash ]] && fun_insta || fun_ip
clear
[[ -e /root/name ]] && figlet -p -f slant < /root/name || echo -e "\033[7;49;35m    =====>>â–ºâ–º ðŸ² New NexuserðŸ’¥VPS ðŸ² â—„â—„<<=====      \033[0m"
fileon=$(ls -la /var/www/html | grep "yaml" | wc -l)
filelo=$(ls -la /root/.config/clash | grep "yaml" | wc -l)
cd
msg -bar3
echo -e "\033[1;37m ✬  Linux Dist: $(less /etc/issue.net)\033[0m"
msg -bar3
echo -e "\033[1;37m ✬ Ficheros Online:	$fileon  ✬ Ficheros Locales: $filelo\033[0m"
msg -bar3
echo -e "\033[1;37m - Menu Iterativo Clash for Android - Nexuser \033[0m"
msg -bar3
echo -e "\033[1;37mSeleccione :    Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
unset yesno
echo -e " DESEAS CONTINUAR CON LA CARGA DE CONFIG CLASH?"
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
unset yesno numwt
#[[ -e /root/name ]] && figlet -p -f slant < /root/name || echo -e "\033[7;49;35m    =====>>â–ºâ–º ðŸ² New NexuserðŸ’¥VPS ðŸ² â—„â—„<<=====      \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m \033[1;33m"
echo -e "\033[1;33m ✬ Ingresa tu Whatsapp junto a tu codigo de Pais"
read -p " Ejemplo: +593987072611 : " numwt
if [[ -z $numwt ]]; then
numwt='+593987072611'
fi
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m \033[1;33m"
echo -e "\033[1;33m ✬ Ingresa Clase de Servidor ( Gratis - PREMIUM )"
read -p " Ejemplo: PREMIUM : " srvip
if [[ -z $srvip ]]; then
srvip="NewADM"
fi
	while :
	do
	[[ -z ${opcion} ]] || break
		clear
		echo -e " ESCOJE TU METODO DE SELECCION "
		echo -e "  "
		echo -e " SINO CONOCES DE ESTO, ESCOJE 2 "
		echo -e "  "
		msg -bar
		echo -e "1 - SELECTOR RULES"
		echo -e "2 - SELECTOR GLOBAL"
		msg -bar
		echo -e " 0) CANCELAR"
		msg -bar
		read -p " ESCOJE : " opcion
		case $opcion in
			1)configINIT_rule "$opcion"
			break;;
			2)configINIT_global "$opcion"
			break;;
			0) break;;
			*) echo -e "\n selecione una opcion del 0 al 2" && sleep 0.3s;;
		esac
	done
INITClash
fi
