#!/bin/bash
FECHA=$(date +"%Y-%m-%d")


cowsay -f eyes " [VPSMOD]-[PSIPHON]" | lolcat







echo "----------------------------------------------"|lolcat
echo  "1) Instalar Server Psiphon"
echo  "2) Desinstalar Servicio Psiphon"
echo  "3) Encender Servicio Psiphon"
echo  "4) Configuracion Servicio Psiphon"
echo  "5) Volver al Menu" 
echo "----------------------------------------------"|lolcat
#leemos del teclado

echo "Selecciona una opcion:"

read n

case $n in
        1) bash /etc/adm-lite/install;;
        2) bash /etc/adm-lite/uninstall;;
        3) bash /etc/adm-lite/on;;
        4) bash /etc/adm-lite/config;;
        5) bash /etc/newadm/menu;;
        *)echo "Opcion incorrecta ";;

esac
