#!/bin/bash
FECHA=$(date +"%Y-%m-%d")


cowsay -f eyes " [VPSMOD]-[PSIPHON]" | lolcat







echo "----------------------------------------------"|lolcat
echo  "1) Instalar Server UDP"
echo  "2) Encender Servicio UDP"
echo  "3) Detener Servicio UDP"
echo  "4) Crear Cuenta UDP"
echo  "5) Volver al Menu"
echo "----------------------------------------------"|lolcat
#leemos del teclado

echo "Selecciona una opcion:"

read n

case $n in
        1) bash /etc/adm-lite/instudp;;
        2) bash /etc/adm-lite/upudp;;
        3) bash /etc/adm-lite/offudp;;
        4) bash /etc/ger-frm/Crear-Demo.sh ;;
        5) bash /etc/newadm/menu;;
        *)echo "Opcion incorrecta ";;

esac
